// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Params {
    /// minted_denom is the denomination of the coin expected to be minted by the
    /// minting module. Pool-incentives module doesn’t actually mint the coin
    /// itself, but rather manages the distribution of coins that matches the
    /// defined minted_denom.
    #[prost(string, tag = "1")]
    pub minted_denom: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LockableDurationsInfo {
    #[prost(message, repeated, tag = "1")]
    pub lockable_durations: ::prost::alloc::vec::Vec<::prost_types::Duration>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DistrInfo {
    #[prost(string, tag = "1")]
    pub total_weight: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub records: ::prost::alloc::vec::Vec<DistrRecord>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DistrRecord {
    #[prost(uint64, tag = "1")]
    pub gauge_id: u64,
    #[prost(string, tag = "2")]
    pub weight: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PoolToGauge {
    #[prost(uint64, tag = "1")]
    pub pool_id: u64,
    #[prost(uint64, tag = "2")]
    pub gauge_id: u64,
    #[prost(message, optional, tag = "3")]
    pub duration: ::core::option::Option<::prost_types::Duration>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AnyPoolToInternalGauges {
    #[prost(message, repeated, tag = "2")]
    pub pool_to_gauge: ::prost::alloc::vec::Vec<PoolToGauge>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConcentratedPoolToNoLockGauges {
    #[prost(message, repeated, tag = "1")]
    pub pool_to_gauge: ::prost::alloc::vec::Vec<PoolToGauge>,
}
/// MigrationRecords contains all the links between balancer and concentrated
/// pools.
///
/// This is copied over from the gamm proto file in order to circumnavigate
/// the circular dependency between the two modules.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MigrationRecords {
    #[prost(message, repeated, tag = "1")]
    pub balancer_to_concentrated_pool_links: ::prost::alloc::vec::Vec<BalancerToConcentratedPoolLink>,
}
/// BalancerToConcentratedPoolLink defines a single link between a single
/// balancer pool and a single concentrated liquidity pool. This link is used to
/// allow a balancer pool to migrate to a single canonical full range
/// concentrated liquidity pool position
/// A balancer pool can be linked to a maximum of one cl pool, and a cl pool can
/// be linked to a maximum of one balancer pool.
///
/// This is copied over from the gamm proto file in order to circumnavigate
/// the circular dependency between the two modules.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct BalancerToConcentratedPoolLink {
    #[prost(uint64, tag = "1")]
    pub balancer_pool_id: u64,
    #[prost(uint64, tag = "2")]
    pub cl_pool_id: u64,
}
// @@protoc_insertion_point(module)
