// @generated
// This file is @generated by prost-build.
/// A TWAP record should be indexed in state by pool_id, (asset pair), timestamp
/// The asset pair assets should be lexicographically sorted.
/// Technically (pool_id, asset_0_denom, asset_1_denom, height) do not need to
/// appear in the struct however we view this as the wrong performance tradeoff
/// given SDK today. Would rather we optimize for readability and correctness,
/// than an optimal state storage format. The system bottleneck is elsewhere for
/// now.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TwapRecord {
    #[prost(uint64, tag = "1")]
    pub pool_id: u64,
    /// Lexicographically smaller denom of the pair
    #[prost(string, tag = "2")]
    pub asset0_denom: ::prost::alloc::string::String,
    /// Lexicographically larger denom of the pair
    #[prost(string, tag = "3")]
    pub asset1_denom: ::prost::alloc::string::String,
    /// height this record corresponds to, for debugging purposes
    #[prost(int64, tag = "4")]
    pub height: i64,
    /// This field should only exist until we have a global registry in the state
    /// machine, mapping prior block heights within {TIME RANGE} to times.
    #[prost(message, optional, tag = "5")]
    pub time: ::core::option::Option<::prost_types::Timestamp>,
    /// We store the last spot prices in the struct, so that we can interpolate
    /// accumulator values for times between when accumulator records are stored.
    #[prost(string, tag = "6")]
    pub p0_last_spot_price: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub p1_last_spot_price: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub p0_arithmetic_twap_accumulator: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub p1_arithmetic_twap_accumulator: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub geometric_twap_accumulator: ::prost::alloc::string::String,
    /// This field contains the time in which the last spot price error occurred.
    /// It is used to alert the caller if they are getting a potentially erroneous
    /// TWAP, due to an unforeseen underlying error.
    #[prost(message, optional, tag = "11")]
    pub last_error_time: ::core::option::Option<::prost_types::Timestamp>,
}
/// PruningState allows us to spread out the pruning of TWAP records over time,
/// instead of pruning all at once at the end of the epoch.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PruningState {
    /// is_pruning is true if the pruning process is ongoing.
    /// This tells the module to continue pruning the TWAP records
    /// at the EndBlock.
    #[prost(bool, tag = "1")]
    pub is_pruning: bool,
    /// last_kept_time is the time of the last kept TWAP record.
    /// This is used to determine all TWAP records that are older than
    /// last_kept_time and should be pruned.
    #[prost(message, optional, tag = "2")]
    pub last_kept_time: ::core::option::Option<::prost_types::Timestamp>,
    /// Deprecated: This field is deprecated.
    #[deprecated]
    #[prost(bytes = "vec", tag = "3")]
    pub last_key_seen: ::prost::alloc::vec::Vec<u8>,
    /// last_seen_pool_id is the pool_id that we will begin pruning in the next
    /// block. This value starts at the highest pool_id at time of epoch, and
    /// decreases until it reaches 1. When it reaches 1, the pruning
    /// process is complete.
    #[prost(uint64, tag = "4")]
    pub last_seen_pool_id: u64,
}
// @@protoc_insertion_point(module)
