// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.32.0
// source: osmosis/txfees/v1beta1/feetoken.proto

package types

import (
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FeeToken is a struct that specifies a coin denom, and pool ID pair.
// This marks the token as eligible for use as a tx fee asset in Osmosis.
// Its price in osmo is derived through looking at the provided pool ID.
// The pool ID must have osmo as one of its assets.
type FeeToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Denom  string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	PoolID uint64 `protobuf:"varint,2,opt,name=poolID,proto3" json:"poolID,omitempty"`
}

func (x *FeeToken) Reset() {
	*x = FeeToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_osmosis_txfees_v1beta1_feetoken_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeeToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeToken) ProtoMessage() {}

func (x *FeeToken) ProtoReflect() protoreflect.Message {
	mi := &file_osmosis_txfees_v1beta1_feetoken_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeToken.ProtoReflect.Descriptor instead.
func (*FeeToken) Descriptor() ([]byte, []int) {
	return file_osmosis_txfees_v1beta1_feetoken_proto_rawDescGZIP(), []int{0}
}

func (x *FeeToken) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *FeeToken) GetPoolID() uint64 {
	if x != nil {
		return x.PoolID
	}
	return 0
}

var File_osmosis_txfees_v1beta1_feetoken_proto protoreflect.FileDescriptor

var file_osmosis_txfees_v1beta1_feetoken_proto_rawDesc = []byte{
	0x0a, 0x25, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x69, 0x73, 0x2f, 0x74, 0x78, 0x66, 0x65, 0x65, 0x73,
	0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2f, 0x66, 0x65, 0x65, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x69, 0x73,
	0x2e, 0x74, 0x78, 0x66, 0x65, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x1a,
	0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x64, 0x0a, 0x08, 0x46, 0x65, 0x65, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x26, 0x0a, 0x05, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x10, 0xf2, 0xde, 0x1f, 0x0c, 0x79, 0x61, 0x6d, 0x6c, 0x3a, 0x22, 0x64, 0x65, 0x6e, 0x6f,
	0x6d, 0x22, 0x52, 0x05, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x12, 0x2a, 0x0a, 0x06, 0x70, 0x6f, 0x6f,
	0x6c, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x42, 0x12, 0xf2, 0xde, 0x1f, 0x0e, 0x79,
	0x61, 0x6d, 0x6c, 0x3a, 0x22, 0x70, 0x6f, 0x6f, 0x6c, 0x5f, 0x69, 0x64, 0x22, 0x52, 0x06, 0x70,
	0x6f, 0x6f, 0x6c, 0x49, 0x44, 0x3a, 0x04, 0xe8, 0xa0, 0x1f, 0x01, 0x42, 0x34, 0x5a, 0x32, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x69,
	0x73, 0x2d, 0x6c, 0x61, 0x62, 0x73, 0x2f, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x69, 0x73, 0x2f, 0x76,
	0x33, 0x31, 0x2f, 0x78, 0x2f, 0x74, 0x78, 0x66, 0x65, 0x65, 0x73, 0x2f, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_osmosis_txfees_v1beta1_feetoken_proto_rawDescOnce sync.Once
	file_osmosis_txfees_v1beta1_feetoken_proto_rawDescData = file_osmosis_txfees_v1beta1_feetoken_proto_rawDesc
)

func file_osmosis_txfees_v1beta1_feetoken_proto_rawDescGZIP() []byte {
	file_osmosis_txfees_v1beta1_feetoken_proto_rawDescOnce.Do(func() {
		file_osmosis_txfees_v1beta1_feetoken_proto_rawDescData = protoimpl.X.CompressGZIP(file_osmosis_txfees_v1beta1_feetoken_proto_rawDescData)
	})
	return file_osmosis_txfees_v1beta1_feetoken_proto_rawDescData
}

var file_osmosis_txfees_v1beta1_feetoken_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_osmosis_txfees_v1beta1_feetoken_proto_goTypes = []interface{}{
	(*FeeToken)(nil), // 0: osmosis.txfees.v1beta1.FeeToken
}
var file_osmosis_txfees_v1beta1_feetoken_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_osmosis_txfees_v1beta1_feetoken_proto_init() }
func file_osmosis_txfees_v1beta1_feetoken_proto_init() {
	if File_osmosis_txfees_v1beta1_feetoken_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_osmosis_txfees_v1beta1_feetoken_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeeToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_osmosis_txfees_v1beta1_feetoken_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osmosis_txfees_v1beta1_feetoken_proto_goTypes,
		DependencyIndexes: file_osmosis_txfees_v1beta1_feetoken_proto_depIdxs,
		MessageInfos:      file_osmosis_txfees_v1beta1_feetoken_proto_msgTypes,
	}.Build()
	File_osmosis_txfees_v1beta1_feetoken_proto = out.File
	file_osmosis_txfees_v1beta1_feetoken_proto_rawDesc = nil
	file_osmosis_txfees_v1beta1_feetoken_proto_goTypes = nil
	file_osmosis_txfees_v1beta1_feetoken_proto_depIdxs = nil
}
