// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.32.0
// source: cosmos/epochs/v1beta1/events.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventEpochEnd is an event emitted when an epoch end.
type EventEpochEnd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EpochNumber int64 `protobuf:"varint,1,opt,name=epoch_number,json=epochNumber,proto3" json:"epoch_number,omitempty"`
}

func (x *EventEpochEnd) Reset() {
	*x = EventEpochEnd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cosmos_epochs_v1beta1_events_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventEpochEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEpochEnd) ProtoMessage() {}

func (x *EventEpochEnd) ProtoReflect() protoreflect.Message {
	mi := &file_cosmos_epochs_v1beta1_events_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEpochEnd.ProtoReflect.Descriptor instead.
func (*EventEpochEnd) Descriptor() ([]byte, []int) {
	return file_cosmos_epochs_v1beta1_events_proto_rawDescGZIP(), []int{0}
}

func (x *EventEpochEnd) GetEpochNumber() int64 {
	if x != nil {
		return x.EpochNumber
	}
	return 0
}

// EventEpochStart is an event emitted when an epoch start.
type EventEpochStart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EpochNumber    int64 `protobuf:"varint,1,opt,name=epoch_number,json=epochNumber,proto3" json:"epoch_number,omitempty"`
	EpochStartTime int64 `protobuf:"varint,2,opt,name=epoch_start_time,json=epochStartTime,proto3" json:"epoch_start_time,omitempty"`
}

func (x *EventEpochStart) Reset() {
	*x = EventEpochStart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cosmos_epochs_v1beta1_events_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventEpochStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEpochStart) ProtoMessage() {}

func (x *EventEpochStart) ProtoReflect() protoreflect.Message {
	mi := &file_cosmos_epochs_v1beta1_events_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEpochStart.ProtoReflect.Descriptor instead.
func (*EventEpochStart) Descriptor() ([]byte, []int) {
	return file_cosmos_epochs_v1beta1_events_proto_rawDescGZIP(), []int{1}
}

func (x *EventEpochStart) GetEpochNumber() int64 {
	if x != nil {
		return x.EpochNumber
	}
	return 0
}

func (x *EventEpochStart) GetEpochStartTime() int64 {
	if x != nil {
		return x.EpochStartTime
	}
	return 0
}

var File_cosmos_epochs_v1beta1_events_proto protoreflect.FileDescriptor

var file_cosmos_epochs_v1beta1_events_proto_rawDesc = []byte{
	0x0a, 0x22, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2f, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x73, 0x2f,
	0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x65, 0x70, 0x6f,
	0x63, 0x68, 0x73, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x22, 0x32, 0x0a, 0x0d, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x45, 0x6e, 0x64, 0x12, 0x21, 0x0a, 0x0c,
	0x65, 0x70, 0x6f, 0x63, 0x68, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0b, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22,
	0x5e, 0x0a, 0x0f, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x5f, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x10, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x5f, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0e, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x42,
	0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f,
	0x73, 0x6d, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2d, 0x73, 0x64, 0x6b, 0x2f,
	0x78, 0x2f, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x73, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cosmos_epochs_v1beta1_events_proto_rawDescOnce sync.Once
	file_cosmos_epochs_v1beta1_events_proto_rawDescData = file_cosmos_epochs_v1beta1_events_proto_rawDesc
)

func file_cosmos_epochs_v1beta1_events_proto_rawDescGZIP() []byte {
	file_cosmos_epochs_v1beta1_events_proto_rawDescOnce.Do(func() {
		file_cosmos_epochs_v1beta1_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_cosmos_epochs_v1beta1_events_proto_rawDescData)
	})
	return file_cosmos_epochs_v1beta1_events_proto_rawDescData
}

var file_cosmos_epochs_v1beta1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cosmos_epochs_v1beta1_events_proto_goTypes = []interface{}{
	(*EventEpochEnd)(nil),   // 0: cosmos.epochs.v1beta1.EventEpochEnd
	(*EventEpochStart)(nil), // 1: cosmos.epochs.v1beta1.EventEpochStart
}
var file_cosmos_epochs_v1beta1_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cosmos_epochs_v1beta1_events_proto_init() }
func file_cosmos_epochs_v1beta1_events_proto_init() {
	if File_cosmos_epochs_v1beta1_events_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cosmos_epochs_v1beta1_events_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventEpochEnd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cosmos_epochs_v1beta1_events_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventEpochStart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cosmos_epochs_v1beta1_events_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cosmos_epochs_v1beta1_events_proto_goTypes,
		DependencyIndexes: file_cosmos_epochs_v1beta1_events_proto_depIdxs,
		MessageInfos:      file_cosmos_epochs_v1beta1_events_proto_msgTypes,
	}.Build()
	File_cosmos_epochs_v1beta1_events_proto = out.File
	file_cosmos_epochs_v1beta1_events_proto_rawDesc = nil
	file_cosmos_epochs_v1beta1_events_proto_goTypes = nil
	file_cosmos_epochs_v1beta1_events_proto_depIdxs = nil
}
