// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.32.0
// source: ibc/core/commitment/v2/commitment.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MerklePath is the path used to verify commitment proofs, which can be an
// arbitrary structured object (defined by a commitment type).
// ICS-23 verification supports membership proofs for nested merkle trees.
// The ICS-24 standard provable keys MUST be stored in the lowest level tree with an optional prefix.
// The IC24 provable tree may then be stored in a higher level tree(s) that hash up to the root hash
// stored in the consensus state of the client.
// Each element of the path represents the key of a merkle tree from the root to the leaf.
// The elements of the path before the final element must be the path to the tree that contains
// the ICS24 provable store. Thus, it should remain constant for all ICS24 proofs.
// The final element of the path is the key of the leaf in the ICS24 provable store,
// Thus IBC core will append the ICS24 path to the final element of the MerklePath
// stored in the counterparty to create the full path to the leaf for proof verification.
// Examples:
// Cosmos SDK:
// The Cosmos SDK commits to a multi-tree where each store is an IAVL tree and all store hashes
// are hashed in a simple merkle tree to get the final root hash. Thus, the MerklePath in the counterparty
// MerklePrefix has the following structure: ["ibc", ""]
// The core IBC handler will append the ICS24 path to the final element of the MerklePath
// like so: ["ibc", "{packetCommitmentPath}"] which will then be used for final verification.
// Ethereum:
// The Ethereum client commits to a single Patricia merkle trie. The ICS24 provable store is managed
// by the smart contract state. Each smart contract has a specific prefix reserved within the global trie.
// Thus the MerklePath in the counterparty is the prefix to the smart contract state in the global trie.
// Since there is only one tree in the commitment structure of ethereum the MerklePath in the counterparty
// MerklePrefix has the following structure: ["IBCCoreContractAddressStoragePrefix"]
// The core IBC handler will append the ICS24 path to the final element of the MerklePath
// like so: ["IBCCoreContractAddressStoragePrefix{packetCommitmentPath}"] which will then be used for final
// verification. Thus the MerklePath in the counterparty MerklePrefix is the nested key path from the root hash of the
// consensus state down to the ICS24 provable store. The IBC handler retrieves the counterparty key path to the ICS24
// provable store from the MerklePath and appends the ICS24 path to get the final key path to the value being verified
// by the client against the root hash in the client's consensus state.
type MerklePath struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyPath [][]byte `protobuf:"bytes,1,rep,name=key_path,json=keyPath,proto3" json:"key_path,omitempty"`
}

func (x *MerklePath) Reset() {
	*x = MerklePath{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ibc_core_commitment_v2_commitment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MerklePath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerklePath) ProtoMessage() {}

func (x *MerklePath) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_commitment_v2_commitment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerklePath.ProtoReflect.Descriptor instead.
func (*MerklePath) Descriptor() ([]byte, []int) {
	return file_ibc_core_commitment_v2_commitment_proto_rawDescGZIP(), []int{0}
}

func (x *MerklePath) GetKeyPath() [][]byte {
	if x != nil {
		return x.KeyPath
	}
	return nil
}

var File_ibc_core_commitment_v2_commitment_proto protoreflect.FileDescriptor

var file_ibc_core_commitment_v2_commitment_proto_rawDesc = []byte{
	0x0a, 0x27, 0x69, 0x62, 0x63, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x76, 0x32, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d,
	0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x69, 0x62, 0x63, 0x2e, 0x63,
	0x6f, 0x72, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76,
	0x32, 0x22, 0x27, 0x0a, 0x0a, 0x4d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12,
	0x19, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0c, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x50, 0x61, 0x74, 0x68, 0x42, 0x42, 0x5a, 0x40, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2f,
	0x69, 0x62, 0x63, 0x2d, 0x67, 0x6f, 0x2f, 0x76, 0x31, 0x30, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c,
	0x65, 0x73, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x32, 0x33, 0x2d, 0x63, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x76, 0x32, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ibc_core_commitment_v2_commitment_proto_rawDescOnce sync.Once
	file_ibc_core_commitment_v2_commitment_proto_rawDescData = file_ibc_core_commitment_v2_commitment_proto_rawDesc
)

func file_ibc_core_commitment_v2_commitment_proto_rawDescGZIP() []byte {
	file_ibc_core_commitment_v2_commitment_proto_rawDescOnce.Do(func() {
		file_ibc_core_commitment_v2_commitment_proto_rawDescData = protoimpl.X.CompressGZIP(file_ibc_core_commitment_v2_commitment_proto_rawDescData)
	})
	return file_ibc_core_commitment_v2_commitment_proto_rawDescData
}

var file_ibc_core_commitment_v2_commitment_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ibc_core_commitment_v2_commitment_proto_goTypes = []interface{}{
	(*MerklePath)(nil), // 0: ibc.core.commitment.v2.MerklePath
}
var file_ibc_core_commitment_v2_commitment_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ibc_core_commitment_v2_commitment_proto_init() }
func file_ibc_core_commitment_v2_commitment_proto_init() {
	if File_ibc_core_commitment_v2_commitment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ibc_core_commitment_v2_commitment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MerklePath); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ibc_core_commitment_v2_commitment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ibc_core_commitment_v2_commitment_proto_goTypes,
		DependencyIndexes: file_ibc_core_commitment_v2_commitment_proto_depIdxs,
		MessageInfos:      file_ibc_core_commitment_v2_commitment_proto_msgTypes,
	}.Build()
	File_ibc_core_commitment_v2_commitment_proto = out.File
	file_ibc_core_commitment_v2_commitment_proto_rawDesc = nil
	file_ibc_core_commitment_v2_commitment_proto_goTypes = nil
	file_ibc_core_commitment_v2_commitment_proto_depIdxs = nil
}
