// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.32.0
// source: cosmos/app/v1alpha1/module.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ModuleDescriptor describes an app module.
type ModuleDescriptor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// go_import names the package that should be imported by an app to load the
	// module in the runtime module registry. It is required to make debugging
	// of configuration errors easier for users.
	GoImport string `protobuf:"bytes,1,opt,name=go_import,json=goImport,proto3" json:"go_import,omitempty"`
	// use_package refers to a protobuf package that this module
	// uses and exposes to the world. In an app, only one module should "use"
	// or own a single protobuf package. It is assumed that the module uses
	// all of the .proto files in a single package.
	UsePackage []*PackageReference `protobuf:"bytes,2,rep,name=use_package,json=usePackage,proto3" json:"use_package,omitempty"`
	// can_migrate_from defines which module versions this module can migrate
	// state from. The framework will check that one module version is able to
	// migrate from a previous module version before attempting to update its
	// config. It is assumed that modules can transitively migrate from earlier
	// versions. For instance if v3 declares it can migrate from v2, and v2
	// declares it can migrate from v1, the framework knows how to migrate
	// from v1 to v3, assuming all 3 module versions are registered at runtime.
	CanMigrateFrom []*MigrateFromInfo `protobuf:"bytes,3,rep,name=can_migrate_from,json=canMigrateFrom,proto3" json:"can_migrate_from,omitempty"`
}

func (x *ModuleDescriptor) Reset() {
	*x = ModuleDescriptor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cosmos_app_v1alpha1_module_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleDescriptor) ProtoMessage() {}

func (x *ModuleDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_cosmos_app_v1alpha1_module_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleDescriptor.ProtoReflect.Descriptor instead.
func (*ModuleDescriptor) Descriptor() ([]byte, []int) {
	return file_cosmos_app_v1alpha1_module_proto_rawDescGZIP(), []int{0}
}

func (x *ModuleDescriptor) GetGoImport() string {
	if x != nil {
		return x.GoImport
	}
	return ""
}

func (x *ModuleDescriptor) GetUsePackage() []*PackageReference {
	if x != nil {
		return x.UsePackage
	}
	return nil
}

func (x *ModuleDescriptor) GetCanMigrateFrom() []*MigrateFromInfo {
	if x != nil {
		return x.CanMigrateFrom
	}
	return nil
}

// PackageReference is a reference to a protobuf package used by a module.
type PackageReference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name is the fully-qualified name of the package.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// revision is the optional revision of the package that is being used.
	// Protobuf packages used in Cosmos should generally have a major version
	// as the last part of the package name, ex. foo.bar.baz.v1.
	// The revision of a package can be thought of as the minor version of a
	// package which has additional backwards compatible definitions that weren't
	// present in a previous version.
	//
	// A package should indicate its revision with a source code comment
	// above the package declaration in one of its files containing the
	// text "Revision N" where N is an integer revision. All packages start
	// at revision 0 the first time they are released in a module.
	//
	// When a new version of a module is released and items are added to existing
	// .proto files, these definitions should contain comments of the form
	// "Since: Revision N" where N is an integer revision.
	//
	// When the module runtime starts up, it will check the pinned proto
	// image and panic if there are runtime protobuf definitions that are not
	// in the pinned descriptor which do not have
	// a "Since Revision N" comment or have a "Since Revision N" comment where
	// N is <= to the revision specified here. This indicates that the protobuf
	// files have been updated, but the pinned file descriptor hasn't.
	//
	// If there are items in the pinned file descriptor with a revision
	// greater than the value indicated here, this will also cause a panic
	// as it may mean that the pinned descriptor for a legacy module has been
	// improperly updated or that there is some other versioning discrepancy.
	// Runtime protobuf definitions will also be checked for compatibility
	// with pinned file descriptors to make sure there are no incompatible changes.
	//
	// This behavior ensures that:
	//   - pinned proto images are up-to-date
	//   - protobuf files are carefully annotated with revision comments which
	//     are important good client UX
	//   - protobuf files are changed in backwards and forwards compatible ways
	Revision uint32 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
}

func (x *PackageReference) Reset() {
	*x = PackageReference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cosmos_app_v1alpha1_module_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PackageReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageReference) ProtoMessage() {}

func (x *PackageReference) ProtoReflect() protoreflect.Message {
	mi := &file_cosmos_app_v1alpha1_module_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageReference.ProtoReflect.Descriptor instead.
func (*PackageReference) Descriptor() ([]byte, []int) {
	return file_cosmos_app_v1alpha1_module_proto_rawDescGZIP(), []int{1}
}

func (x *PackageReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PackageReference) GetRevision() uint32 {
	if x != nil {
		return x.Revision
	}
	return 0
}

// MigrateFromInfo is information on a module version that a newer module
// can migrate from.
type MigrateFromInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// module is the fully-qualified protobuf name of the module config object
	// for the previous module version, ex: "cosmos.group.module.v1.Module".
	Module string `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
}

func (x *MigrateFromInfo) Reset() {
	*x = MigrateFromInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cosmos_app_v1alpha1_module_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MigrateFromInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateFromInfo) ProtoMessage() {}

func (x *MigrateFromInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cosmos_app_v1alpha1_module_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateFromInfo.ProtoReflect.Descriptor instead.
func (*MigrateFromInfo) Descriptor() ([]byte, []int) {
	return file_cosmos_app_v1alpha1_module_proto_rawDescGZIP(), []int{2}
}

func (x *MigrateFromInfo) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

var file_cosmos_app_v1alpha1_module_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*ModuleDescriptor)(nil),
		Field:         57193479,
		Name:          "cosmos.app.v1alpha1.module",
		Tag:           "bytes,57193479,opt,name=module",
		Filename:      "cosmos/app/v1alpha1/module.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// module indicates that this proto type is a config object for an app module
	// and optionally provides other descriptive information about the module.
	// It is recommended that a new module config object and go module is versioned
	// for every state machine breaking version of a module. The recommended
	// pattern for doing this is to put module config objects in a separate proto
	// package from the API they expose. Ex: the cosmos.group.v1 API would be
	// exposed by module configs cosmos.group.module.v1, cosmos.group.module.v2, etc.
	//
	// optional cosmos.app.v1alpha1.ModuleDescriptor module = 57193479;
	E_Module = &file_cosmos_app_v1alpha1_module_proto_extTypes[0]
)

var File_cosmos_app_v1alpha1_module_proto protoreflect.FileDescriptor

var file_cosmos_app_v1alpha1_module_proto_rawDesc = []byte{
	0x0a, 0x20, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x13, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc7, 0x01, 0x0a, 0x10, 0x4d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x12, 0x1b,
	0x0a, 0x09, 0x67, 0x6f, 0x5f, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x67, 0x6f, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x46, 0x0a, 0x0b, 0x75,
	0x73, 0x65, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x25, 0x2e, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x50, 0x61, 0x63, 0x6b,
	0x61, 0x67, 0x65, 0x12, 0x4e, 0x0a, 0x10, 0x63, 0x61, 0x6e, 0x5f, 0x6d, 0x69, 0x67, 0x72, 0x61,
	0x74, 0x65, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e,
	0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x31, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x0e, 0x63, 0x61, 0x6e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x46,
	0x72, 0x6f, 0x6d, 0x22, 0x42, 0x0a, 0x10, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72,
	0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x72,
	0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x29, 0x0a, 0x0f, 0x4d, 0x69, 0x67, 0x72, 0x61,
	0x74, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x3a, 0x61, 0x0a, 0x06, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x1f, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x87, 0xe8,
	0xa2, 0x1b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e,
	0x61, 0x70, 0x70, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x4d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x52, 0x06, 0x6d,
	0x6f, 0x64, 0x75, 0x6c, 0x65, 0x42, 0x2b, 0x5a, 0x29, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73,
	0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x64, 0x65, 0x70, 0x69, 0x6e, 0x6a, 0x65, 0x63, 0x74, 0x2f,
	0x61, 0x70, 0x70, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cosmos_app_v1alpha1_module_proto_rawDescOnce sync.Once
	file_cosmos_app_v1alpha1_module_proto_rawDescData = file_cosmos_app_v1alpha1_module_proto_rawDesc
)

func file_cosmos_app_v1alpha1_module_proto_rawDescGZIP() []byte {
	file_cosmos_app_v1alpha1_module_proto_rawDescOnce.Do(func() {
		file_cosmos_app_v1alpha1_module_proto_rawDescData = protoimpl.X.CompressGZIP(file_cosmos_app_v1alpha1_module_proto_rawDescData)
	})
	return file_cosmos_app_v1alpha1_module_proto_rawDescData
}

var file_cosmos_app_v1alpha1_module_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cosmos_app_v1alpha1_module_proto_goTypes = []interface{}{
	(*ModuleDescriptor)(nil),            // 0: cosmos.app.v1alpha1.ModuleDescriptor
	(*PackageReference)(nil),            // 1: cosmos.app.v1alpha1.PackageReference
	(*MigrateFromInfo)(nil),             // 2: cosmos.app.v1alpha1.MigrateFromInfo
	(*descriptorpb.MessageOptions)(nil), // 3: google.protobuf.MessageOptions
}
var file_cosmos_app_v1alpha1_module_proto_depIdxs = []int32{
	1, // 0: cosmos.app.v1alpha1.ModuleDescriptor.use_package:type_name -> cosmos.app.v1alpha1.PackageReference
	2, // 1: cosmos.app.v1alpha1.ModuleDescriptor.can_migrate_from:type_name -> cosmos.app.v1alpha1.MigrateFromInfo
	3, // 2: cosmos.app.v1alpha1.module:extendee -> google.protobuf.MessageOptions
	0, // 3: cosmos.app.v1alpha1.module:type_name -> cosmos.app.v1alpha1.ModuleDescriptor
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	3, // [3:4] is the sub-list for extension type_name
	2, // [2:3] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cosmos_app_v1alpha1_module_proto_init() }
func file_cosmos_app_v1alpha1_module_proto_init() {
	if File_cosmos_app_v1alpha1_module_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cosmos_app_v1alpha1_module_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModuleDescriptor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cosmos_app_v1alpha1_module_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PackageReference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cosmos_app_v1alpha1_module_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MigrateFromInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cosmos_app_v1alpha1_module_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_cosmos_app_v1alpha1_module_proto_goTypes,
		DependencyIndexes: file_cosmos_app_v1alpha1_module_proto_depIdxs,
		MessageInfos:      file_cosmos_app_v1alpha1_module_proto_msgTypes,
		ExtensionInfos:    file_cosmos_app_v1alpha1_module_proto_extTypes,
	}.Build()
	File_cosmos_app_v1alpha1_module_proto = out.File
	file_cosmos_app_v1alpha1_module_proto_rawDesc = nil
	file_cosmos_app_v1alpha1_module_proto_goTypes = nil
	file_cosmos_app_v1alpha1_module_proto_depIdxs = nil
}
