// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.32.0
// source: interchain_security/ccv/consumer/v1/consumer.proto

package types

import (
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CrossChainValidator defines the type used to store validator information
// internal to the consumer CCV module.  Note one cross chain validator entry is
// persisted for each consumer validator, where incoming VSC packets update this
// data, which is eventually forwarded to comet for consumer chain consensus.
//
// Note this type is only used internally to the consumer CCV module.
type CrossChainValidator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Power   int64  `protobuf:"varint,2,opt,name=power,proto3" json:"power,omitempty"`
	// pubkey is the consensus public key of the validator, as a Protobuf Any.
	Pubkey *anypb.Any `protobuf:"bytes,3,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	// !!! DEPRECATED !!! opted_out is deprecated because after the introduction of Partial Set Security (PSS)
	// we removed the soft opt-out feature.
	//
	// Deprecated: Do not use.
	OptedOut bool `protobuf:"varint,4,opt,name=opted_out,json=optedOut,proto3" json:"opted_out,omitempty"`
}

func (x *CrossChainValidator) Reset() {
	*x = CrossChainValidator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interchain_security_ccv_consumer_v1_consumer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CrossChainValidator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrossChainValidator) ProtoMessage() {}

func (x *CrossChainValidator) ProtoReflect() protoreflect.Message {
	mi := &file_interchain_security_ccv_consumer_v1_consumer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrossChainValidator.ProtoReflect.Descriptor instead.
func (*CrossChainValidator) Descriptor() ([]byte, []int) {
	return file_interchain_security_ccv_consumer_v1_consumer_proto_rawDescGZIP(), []int{0}
}

func (x *CrossChainValidator) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *CrossChainValidator) GetPower() int64 {
	if x != nil {
		return x.Power
	}
	return 0
}

func (x *CrossChainValidator) GetPubkey() *anypb.Any {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

// Deprecated: Do not use.
func (x *CrossChainValidator) GetOptedOut() bool {
	if x != nil {
		return x.OptedOut
	}
	return false
}

// A record storing the state of a slash packet sent to the provider chain
// which may bounce back and forth until handled by the provider.
//
// Note this type is only used internally to the consumer CCV module.
type SlashRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WaitingOnReply bool                   `protobuf:"varint,1,opt,name=waiting_on_reply,json=waitingOnReply,proto3" json:"waiting_on_reply,omitempty"`
	SendTime       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
}

func (x *SlashRecord) Reset() {
	*x = SlashRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interchain_security_ccv_consumer_v1_consumer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlashRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlashRecord) ProtoMessage() {}

func (x *SlashRecord) ProtoReflect() protoreflect.Message {
	mi := &file_interchain_security_ccv_consumer_v1_consumer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlashRecord.ProtoReflect.Descriptor instead.
func (*SlashRecord) Descriptor() ([]byte, []int) {
	return file_interchain_security_ccv_consumer_v1_consumer_proto_rawDescGZIP(), []int{1}
}

func (x *SlashRecord) GetWaitingOnReply() bool {
	if x != nil {
		return x.WaitingOnReply
	}
	return false
}

func (x *SlashRecord) GetSendTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SendTime
	}
	return nil
}

var File_interchain_security_ccv_consumer_v1_consumer_proto protoreflect.FileDescriptor

var file_interchain_security_ccv_consumer_v1_consumer_proto_rawDesc = []byte{
	0x0a, 0x32, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x73, 0x65, 0x63,
	0x75, 0x72, 0x69, 0x74, 0x79, 0x2f, 0x63, 0x63, 0x76, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d,
	0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x23, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x5f, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x2e, 0x63, 0x63, 0x76, 0x2e, 0x63, 0x6f,
	0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x67, 0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x63, 0x6f, 0x73, 0x6d,
	0x6f, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc9, 0x01, 0x0a, 0x13, 0x43, 0x72, 0x6f, 0x73, 0x73,
	0x43, 0x68, 0x61, 0x69, 0x6e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6f, 0x77, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x61,
	0x0a, 0x06, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x41, 0x6e, 0x79, 0x42, 0x33, 0xf2, 0xde, 0x1f, 0x17, 0x79, 0x61, 0x6d, 0x6c, 0x3a, 0x22,
	0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x5f, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79,
	0x22, 0xca, 0xb4, 0x2d, 0x14, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x6f, 0x2e, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x52, 0x06, 0x70, 0x75, 0x62, 0x6b, 0x65,
	0x79, 0x12, 0x1f, 0x0a, 0x09, 0x6f, 0x70, 0x74, 0x65, 0x64, 0x5f, 0x6f, 0x75, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x42, 0x02, 0x18, 0x01, 0x52, 0x08, 0x6f, 0x70, 0x74, 0x65, 0x64, 0x4f,
	0x75, 0x74, 0x22, 0x7a, 0x0a, 0x0b, 0x53, 0x6c, 0x61, 0x73, 0x68, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x12, 0x28, 0x0a, 0x10, 0x77, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x6f, 0x6e, 0x5f,
	0x72, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x77, 0x61, 0x69,
	0x74, 0x69, 0x6e, 0x67, 0x4f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x41, 0x0a, 0x09, 0x73,
	0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x42, 0x08, 0xc8, 0xde, 0x1f, 0x00,
	0x90, 0xdf, 0x1f, 0x01, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x3f,
	0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x73,
	0x6d, 0x6f, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2d, 0x73,
	0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x2f, 0x76, 0x37, 0x2f, 0x78, 0x2f, 0x63, 0x63, 0x76,
	0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_interchain_security_ccv_consumer_v1_consumer_proto_rawDescOnce sync.Once
	file_interchain_security_ccv_consumer_v1_consumer_proto_rawDescData = file_interchain_security_ccv_consumer_v1_consumer_proto_rawDesc
)

func file_interchain_security_ccv_consumer_v1_consumer_proto_rawDescGZIP() []byte {
	file_interchain_security_ccv_consumer_v1_consumer_proto_rawDescOnce.Do(func() {
		file_interchain_security_ccv_consumer_v1_consumer_proto_rawDescData = protoimpl.X.CompressGZIP(file_interchain_security_ccv_consumer_v1_consumer_proto_rawDescData)
	})
	return file_interchain_security_ccv_consumer_v1_consumer_proto_rawDescData
}

var file_interchain_security_ccv_consumer_v1_consumer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_interchain_security_ccv_consumer_v1_consumer_proto_goTypes = []interface{}{
	(*CrossChainValidator)(nil),   // 0: interchain_security.ccv.consumer.v1.CrossChainValidator
	(*SlashRecord)(nil),           // 1: interchain_security.ccv.consumer.v1.SlashRecord
	(*anypb.Any)(nil),             // 2: google.protobuf.Any
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_interchain_security_ccv_consumer_v1_consumer_proto_depIdxs = []int32{
	2, // 0: interchain_security.ccv.consumer.v1.CrossChainValidator.pubkey:type_name -> google.protobuf.Any
	3, // 1: interchain_security.ccv.consumer.v1.SlashRecord.send_time:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_interchain_security_ccv_consumer_v1_consumer_proto_init() }
func file_interchain_security_ccv_consumer_v1_consumer_proto_init() {
	if File_interchain_security_ccv_consumer_v1_consumer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_interchain_security_ccv_consumer_v1_consumer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CrossChainValidator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interchain_security_ccv_consumer_v1_consumer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlashRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_interchain_security_ccv_consumer_v1_consumer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_interchain_security_ccv_consumer_v1_consumer_proto_goTypes,
		DependencyIndexes: file_interchain_security_ccv_consumer_v1_consumer_proto_depIdxs,
		MessageInfos:      file_interchain_security_ccv_consumer_v1_consumer_proto_msgTypes,
	}.Build()
	File_interchain_security_ccv_consumer_v1_consumer_proto = out.File
	file_interchain_security_ccv_consumer_v1_consumer_proto_rawDesc = nil
	file_interchain_security_ccv_consumer_v1_consumer_proto_goTypes = nil
	file_interchain_security_ccv_consumer_v1_consumer_proto_depIdxs = nil
}
