// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Params {
    /// code_ide_whitelist contains the list of code ids that are allowed to be
    /// instantiated.
    #[prost(uint64, repeated, packed = "false", tag = "1")]
    pub code_id_whitelist: ::prost::alloc::vec::Vec<u64>,
    /// pool_migration_limit is the maximum number of pools that can be migrated
    /// at once via governance proposal. This is to have a constant bound on the
    /// number of pools that can be migrated at once and remove the possibility
    /// of an unlikely scenario of causing a chain halt due to a large migration.
    #[prost(uint64, tag = "2")]
    pub pool_migration_limit: u64,
}
// @@protoc_insertion_point(module)
