// @generated
// This file is @generated by prost-build.
/// Params contains the required set of parameters for the EIP1559 fee market
/// plugin implementation.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Params {
    /// Alpha is the amount we additively increase the learning rate
    /// when it is above or below the target +/- threshold.
    ///
    /// Must be > 0.
    #[prost(string, tag = "1")]
    pub alpha: ::prost::alloc::string::String,
    /// Beta is the amount we multiplicatively decrease the learning rate
    /// when it is within the target +/- threshold.
    ///
    /// Must be \[0, 1\].
    #[prost(string, tag = "2")]
    pub beta: ::prost::alloc::string::String,
    /// Gamma is the threshold for the learning rate. If the learning rate is
    /// above or below the target +/- threshold, we additively increase the
    /// learning rate by Alpha. Otherwise, we multiplicatively decrease the
    /// learning rate by Beta.
    ///
    /// Must be \[0, 0.5\].
    #[prost(string, tag = "3")]
    pub gamma: ::prost::alloc::string::String,
    /// Delta is the amount we additively increase/decrease the gas price when the
    /// net block utilization difference in the window is above/below the target
    /// utilization.
    #[prost(string, tag = "4")]
    pub delta: ::prost::alloc::string::String,
    /// MinBaseGasPrice determines the initial gas price of the module and the
    /// global minimum for the network.
    #[prost(string, tag = "5")]
    pub min_base_gas_price: ::prost::alloc::string::String,
    /// MinLearningRate is the lower bound for the learning rate.
    #[prost(string, tag = "6")]
    pub min_learning_rate: ::prost::alloc::string::String,
    /// MaxLearningRate is the upper bound for the learning rate.
    #[prost(string, tag = "7")]
    pub max_learning_rate: ::prost::alloc::string::String,
    /// MaxBlockUtilization is the maximum block utilization.
    #[prost(uint64, tag = "8")]
    pub max_block_utilization: u64,
    /// Window defines the window size for calculating an adaptive learning rate
    /// over a moving window of blocks.
    #[prost(uint64, tag = "9")]
    pub window: u64,
    /// FeeDenom is the denom that will be used for all fee payments.
    #[prost(string, tag = "10")]
    pub fee_denom: ::prost::alloc::string::String,
    /// Enabled is a boolean that determines whether the EIP1559 fee market is
    /// enabled.
    #[prost(bool, tag = "11")]
    pub enabled: bool,
    /// DistributeFees is a boolean that determines whether the fees are burned or
    /// distributed to all stakers.
    #[prost(bool, tag = "12")]
    pub distribute_fees: bool,
}
// @@protoc_insertion_point(module)
