// @generated
// This file is @generated by prost-build.
/// Params defines the parameters for the module.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Params {
    /// MaximumUnauthenticatedGas defines the maximum amount of gas that can be
    /// used to authenticate a transaction in ante handler without having fee payer
    /// authenticated.
    #[prost(uint64, tag = "1")]
    pub maximum_unauthenticated_gas: u64,
    /// IsSmartAccountActive defines the state of the authenticator.
    /// If set to false, the authenticator module will not be used
    /// and the classic cosmos sdk authentication will be used instead.
    #[prost(bool, tag = "2")]
    pub is_smart_account_active: bool,
    /// CircuitBreakerControllers defines list of addresses that are allowed to
    /// set is_smart_account_active without going through governance.
    #[prost(string, repeated, tag = "3")]
    pub circuit_breaker_controllers: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
// @@protoc_insertion_point(module)
