// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.32.0
// source: ibc/core/client/v2/genesis.proto

package types

import (
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GenesisCounterpartyInfo defines the state associating a client with a counterparty.
type GenesisCounterpartyInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ClientId is the ID of the given client.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// CounterpartyInfo is the counterparty info of the given client.
	CounterpartyInfo *CounterpartyInfo `protobuf:"bytes,2,opt,name=counterparty_info,json=counterpartyInfo,proto3" json:"counterparty_info,omitempty"`
}

func (x *GenesisCounterpartyInfo) Reset() {
	*x = GenesisCounterpartyInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ibc_core_client_v2_genesis_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenesisCounterpartyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisCounterpartyInfo) ProtoMessage() {}

func (x *GenesisCounterpartyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_client_v2_genesis_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisCounterpartyInfo.ProtoReflect.Descriptor instead.
func (*GenesisCounterpartyInfo) Descriptor() ([]byte, []int) {
	return file_ibc_core_client_v2_genesis_proto_rawDescGZIP(), []int{0}
}

func (x *GenesisCounterpartyInfo) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *GenesisCounterpartyInfo) GetCounterpartyInfo() *CounterpartyInfo {
	if x != nil {
		return x.CounterpartyInfo
	}
	return nil
}

// GenesisState defines the ibc client v2 submodule's genesis state.
type GenesisState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// counterparty info for each client
	CounterpartyInfos []*GenesisCounterpartyInfo `protobuf:"bytes,1,rep,name=counterparty_infos,json=counterpartyInfos,proto3" json:"counterparty_infos,omitempty"`
}

func (x *GenesisState) Reset() {
	*x = GenesisState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ibc_core_client_v2_genesis_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenesisState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisState) ProtoMessage() {}

func (x *GenesisState) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_client_v2_genesis_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisState.ProtoReflect.Descriptor instead.
func (*GenesisState) Descriptor() ([]byte, []int) {
	return file_ibc_core_client_v2_genesis_proto_rawDescGZIP(), []int{1}
}

func (x *GenesisState) GetCounterpartyInfos() []*GenesisCounterpartyInfo {
	if x != nil {
		return x.CounterpartyInfos
	}
	return nil
}

var File_ibc_core_client_v2_genesis_proto protoreflect.FileDescriptor

var file_ibc_core_client_v2_genesis_proto_rawDesc = []byte{
	0x0a, 0x20, 0x69, 0x62, 0x63, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x2f, 0x76, 0x32, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x73, 0x69, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x12, 0x69, 0x62, 0x63, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x2e, 0x76, 0x32, 0x1a, 0x25, 0x69, 0x62, 0x63, 0x2f, 0x63, 0x6f, 0x72, 0x65,
	0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x76, 0x32, 0x2f, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x65, 0x72, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x67,
	0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x8f, 0x01, 0x0a, 0x17, 0x47, 0x65, 0x6e, 0x65, 0x73, 0x69, 0x73, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x61, 0x72, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x57, 0x0a, 0x11,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x61, 0x72, 0x74, 0x79, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x69, 0x62, 0x63, 0x2e, 0x63, 0x6f,
	0x72, 0x65, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x32, 0x2e, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x65, 0x72, 0x70, 0x61, 0x72, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x04, 0xc8,
	0xde, 0x1f, 0x00, 0x52, 0x10, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x61, 0x72, 0x74,
	0x79, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x70, 0x0a, 0x0c, 0x47, 0x65, 0x6e, 0x65, 0x73, 0x69, 0x73,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x60, 0x0a, 0x12, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72,
	0x70, 0x61, 0x72, 0x74, 0x79, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x2b, 0x2e, 0x69, 0x62, 0x63, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x2e, 0x76, 0x32, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x73, 0x69, 0x73, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x61, 0x72, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x04,
	0xc8, 0xde, 0x1f, 0x00, 0x52, 0x11, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x61, 0x72,
	0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2f, 0x69, 0x62, 0x63,
	0x2d, 0x67, 0x6f, 0x2f, 0x76, 0x31, 0x30, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2f,
	0x63, 0x6f, 0x72, 0x65, 0x2f, 0x30, 0x32, 0x2d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x76,
	0x32, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ibc_core_client_v2_genesis_proto_rawDescOnce sync.Once
	file_ibc_core_client_v2_genesis_proto_rawDescData = file_ibc_core_client_v2_genesis_proto_rawDesc
)

func file_ibc_core_client_v2_genesis_proto_rawDescGZIP() []byte {
	file_ibc_core_client_v2_genesis_proto_rawDescOnce.Do(func() {
		file_ibc_core_client_v2_genesis_proto_rawDescData = protoimpl.X.CompressGZIP(file_ibc_core_client_v2_genesis_proto_rawDescData)
	})
	return file_ibc_core_client_v2_genesis_proto_rawDescData
}

var file_ibc_core_client_v2_genesis_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ibc_core_client_v2_genesis_proto_goTypes = []interface{}{
	(*GenesisCounterpartyInfo)(nil), // 0: ibc.core.client.v2.GenesisCounterpartyInfo
	(*GenesisState)(nil),            // 1: ibc.core.client.v2.GenesisState
	(*CounterpartyInfo)(nil),        // 2: ibc.core.client.v2.CounterpartyInfo
}
var file_ibc_core_client_v2_genesis_proto_depIdxs = []int32{
	2, // 0: ibc.core.client.v2.GenesisCounterpartyInfo.counterparty_info:type_name -> ibc.core.client.v2.CounterpartyInfo
	0, // 1: ibc.core.client.v2.GenesisState.counterparty_infos:type_name -> ibc.core.client.v2.GenesisCounterpartyInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ibc_core_client_v2_genesis_proto_init() }
func file_ibc_core_client_v2_genesis_proto_init() {
	if File_ibc_core_client_v2_genesis_proto != nil {
		return
	}
	file_ibc_core_client_v2_counterparty_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ibc_core_client_v2_genesis_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenesisCounterpartyInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ibc_core_client_v2_genesis_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenesisState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ibc_core_client_v2_genesis_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ibc_core_client_v2_genesis_proto_goTypes,
		DependencyIndexes: file_ibc_core_client_v2_genesis_proto_depIdxs,
		MessageInfos:      file_ibc_core_client_v2_genesis_proto_msgTypes,
	}.Build()
	File_ibc_core_client_v2_genesis_proto = out.File
	file_ibc_core_client_v2_genesis_proto_rawDesc = nil
	file_ibc_core_client_v2_genesis_proto_goTypes = nil
	file_ibc_core_client_v2_genesis_proto_depIdxs = nil
}
