// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TestMessage {
    #[prost(string, tag = "1")]
    pub foo: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub bar: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TestNestedMessage {
    #[prost(string, tag = "1")]
    pub fuzz: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub msg: ::core::option::Option<TestMessage>,
}
/// Used in shared/p2p/feed_example_test.go
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Puzzle {
    #[prost(string, tag = "1")]
    pub challenge: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub answer: ::prost::alloc::string::String,
}
/// Person and address book example from
/// <https://github.com/protocolbuffers/protobuf/blob/master/examples/addressbook.proto>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Person {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub id: i32,
    #[prost(string, tag = "3")]
    pub email: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "4")]
    pub phones: ::prost::alloc::vec::Vec<person::PhoneNumber>,
    #[prost(message, optional, tag = "5")]
    pub last_updated: ::core::option::Option<::prost_types::Timestamp>,
}
/// Nested message and enum types in `Person`.
pub mod person {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct PhoneNumber {
        #[prost(string, tag = "1")]
        pub number: ::prost::alloc::string::String,
        #[prost(enumeration = "PhoneType", tag = "2")]
        pub r#type: i32,
    }
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum PhoneType {
        Mobile = 0,
        Home = 1,
        Work = 2,
    }
    impl PhoneType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Mobile => "MOBILE",
                Self::Home => "HOME",
                Self::Work => "WORK",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "MOBILE" => Some(Self::Mobile),
                "HOME" => Some(Self::Home),
                "WORK" => Some(Self::Work),
                _ => None,
            }
        }
    }
}
/// Our address book file is just one of these.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddressBook {
    #[prost(message, repeated, tag = "1")]
    pub people: ::prost::alloc::vec::Vec<Person>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TestSimpleMessage {
    #[prost(bytes = "vec", tag = "1")]
    pub foo: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "2")]
    pub bar: u64,
}
// @@protoc_insertion_point(module)
