// @generated
// This file is @generated by prost-build.
/// Params defines the set of IBC transfer parameters.
/// NOTE: To prevent a single token from being transferred, set the
/// TransfersEnabled parameter to true and then set the bank module's SendEnabled
/// parameter for the denomination to false.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Params {
    /// send_enabled enables or disables all cross-chain token transfers from this
    /// chain.
    #[prost(bool, tag = "1")]
    pub send_enabled: bool,
    /// receive_enabled enables or disables all cross-chain token transfers to this
    /// chain.
    #[prost(bool, tag = "2")]
    pub receive_enabled: bool,
}
/// Token defines a struct which represents a token to be transferred.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Token {
    /// the token denomination
    #[prost(message, optional, tag = "1")]
    pub denom: ::core::option::Option<Denom>,
    /// the token amount to be transferred
    #[prost(string, tag = "2")]
    pub amount: ::prost::alloc::string::String,
}
/// Denom holds the base denom of a Token and a trace of the chains it was sent through.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Denom {
    /// the base token denomination
    #[prost(string, tag = "1")]
    pub base: ::prost::alloc::string::String,
    /// the trace of the token
    #[prost(message, repeated, tag = "3")]
    pub trace: ::prost::alloc::vec::Vec<Hop>,
}
/// Hop defines a port ID, channel ID pair specifying a unique "hop" in a trace
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Hop {
    #[prost(string, tag = "1")]
    pub port_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub channel_id: ::prost::alloc::string::String,
}
/// GenesisState defines the ibc-transfer genesis state
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GenesisState {
    #[prost(string, tag = "1")]
    pub port_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub denoms: ::prost::alloc::vec::Vec<Denom>,
    #[prost(message, optional, tag = "3")]
    pub params: ::core::option::Option<Params>,
    /// total_escrowed contains the total amount of tokens escrowed
    /// by the transfer module
    #[prost(message, repeated, tag = "4")]
    pub total_escrowed: ::prost::alloc::vec::Vec<super::super::super::super::cosmos::base::v1beta1::Coin>,
}
// @@protoc_insertion_point(module)
