// @generated
// This file is @generated by prost-build.
/// A span is a single-host view of an operation. A trace is a series of spans
/// (often RPC calls) which nest to form a latency tree. Spans are in the same
/// trace when they share the same trace ID. The parent_id field establishes the
/// position of one span in the tree.
///
/// The root span is where parent_id is Absent and usually has the longest
/// duration in the trace. However, nested asynchronous work can materialize as
/// child spans whose duration exceed the root span.
///
/// Spans usually represent remote activity such as RPC calls, or messaging
/// producers and consumers. However, they can also represent in-process
/// activity in any position of the trace. For example, a root span could
/// represent a server receiving an initial client request. A root span could
/// also represent a scheduled job that has no remote context.
///
/// Encoding notes:
///
/// Epoch timestamp are encoded fixed64 as varint would also be 8 bytes, and more
/// expensive to encode and size. Duration is stored uint64, as often the numbers
/// are quite small.
///
/// Default values are ok, as only natural numbers are used. For example, zero is
/// an invalid timestamp and an invalid duration, false values for debug or shared
/// are ignorable, and zero-length strings also coerce to null.
///
/// The next id is 14.
///
/// Note fields up to 15 take 1 byte to encode. Take care when adding new fields
/// <https://developers.google.com/protocol-buffers/docs/proto3#assigning-tags>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Span {
    /// Randomly generated, unique identifier for a trace, set on all spans within
    /// it.
    ///
    /// This field is required and encoded as 8 or 16 opaque bytes.
    #[prost(bytes = "vec", tag = "1")]
    pub trace_id: ::prost::alloc::vec::Vec<u8>,
    /// The parent span ID or absent if this the root span in a trace.
    #[prost(bytes = "vec", tag = "2")]
    pub parent_id: ::prost::alloc::vec::Vec<u8>,
    /// Unique identifier for this operation within the trace.
    ///
    /// This field is required and encoded as 8 opaque bytes.
    #[prost(bytes = "vec", tag = "3")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    /// When present, used to interpret remote_endpoint
    #[prost(enumeration = "span::Kind", tag = "4")]
    pub kind: i32,
    /// The logical operation this span represents in lowercase (e.g. rpc method).
    /// Leave absent if unknown.
    ///
    /// As these are lookup labels, take care to ensure names are low cardinality.
    /// For example, do not embed variables into the name.
    #[prost(string, tag = "5")]
    pub name: ::prost::alloc::string::String,
    /// Epoch microseconds of the start of this span, possibly absent if
    /// incomplete.
    ///
    /// For example, 1502787600000000 corresponds to 2017-08-15 09:00 UTC
    ///
    /// This value should be set directly by instrumentation, using the most
    /// precise value possible. For example, gettimeofday or multiplying epoch
    /// millis by 1000.
    ///
    /// There are three known edge-cases where this could be reported absent.
    /// - A span was allocated but never started (ex not yet received a timestamp)
    /// - The span's start event was lost
    /// - Data about a completed span (ex tags) were sent after the fact
    #[prost(fixed64, tag = "6")]
    pub timestamp: u64,
    /// Duration in microseconds of the critical path, if known. Durations of less
    /// than one are rounded up. Duration of children can be longer than their
    /// parents due to asynchronous operations.
    ///
    /// For example 150 milliseconds is 150000 microseconds.
    #[prost(uint64, tag = "7")]
    pub duration: u64,
    /// The host that recorded this span, primarily for query by service name.
    ///
    /// Instrumentation should always record this. Usually, absent implies late
    /// data. The IP address corresponding to this is usually the site local or
    /// advertised service address. When present, the port indicates the listen
    /// port.
    #[prost(message, optional, tag = "8")]
    pub local_endpoint: ::core::option::Option<Endpoint>,
    /// When an RPC (or messaging) span, indicates the other side of the
    /// connection.
    ///
    /// By recording the remote endpoint, your trace will contain network context
    /// even if the peer is not tracing. For example, you can record the IP from
    /// the "X-Forwarded-For" header or the service name and socket of a remote
    /// peer.
    #[prost(message, optional, tag = "9")]
    pub remote_endpoint: ::core::option::Option<Endpoint>,
    /// Associates events that explain latency with the time they happened.
    #[prost(message, repeated, tag = "10")]
    pub annotations: ::prost::alloc::vec::Vec<Annotation>,
    /// Tags give your span context for search, viewing and analysis.
    ///
    /// For example, a key "your_app.version" would let you lookup traces by
    /// version. A tag "sql.query" isn't searchable, but it can help in debugging
    /// when viewing a trace.
    #[prost(map = "string, string", tag = "11")]
    pub tags: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    /// True is a request to store this span even if it overrides sampling policy.
    ///
    /// This is true when the "X-B3-Flags" header has a value of 1.
    #[prost(bool, tag = "12")]
    pub debug: bool,
    /// True if we are contributing to a span started by another tracer (ex on a
    /// different host).
    #[prost(bool, tag = "13")]
    pub shared: bool,
}
/// Nested message and enum types in `Span`.
pub mod span {
    /// When present, kind clarifies timestamp, duration and remote_endpoint. When
    /// absent, the span is local or incomplete. Unlike client and server, there
    /// is no direct critical path latency relationship between producer and
    /// consumer spans.
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Kind {
        /// Default value interpreted as absent.
        SpanKindUnspecified = 0,
        /// The span represents the client side of an RPC operation, implying the
        /// following:
        ///
        /// timestamp is the moment a request was sent to the server.
        /// duration is the delay until a response or an error was received.
        /// remote_endpoint is the server.
        Client = 1,
        /// The span represents the server side of an RPC operation, implying the
        /// following:
        ///
        /// timestamp is the moment a client request was received.
        /// duration is the delay until a response was sent or an error.
        /// remote_endpoint is the client.
        Server = 2,
        /// The span represents production of a message to a remote broker, implying
        /// the following:
        ///
        /// timestamp is the moment a message was sent to a destination.
        /// duration is the delay sending the message, such as batching.
        /// remote_endpoint is the broker.
        Producer = 3,
        /// The span represents consumption of a message from a remote broker, not
        /// time spent servicing it. For example, a message processor would be an
        /// in-process child span of a consumer. Consumer spans imply the following:
        ///
        /// timestamp is the moment a message was received from an origin.
        /// duration is the delay consuming the message, such as from backlog.
        /// remote_endpoint is the broker.
        Consumer = 4,
    }
    impl Kind {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::SpanKindUnspecified => "SPAN_KIND_UNSPECIFIED",
                Self::Client => "CLIENT",
                Self::Server => "SERVER",
                Self::Producer => "PRODUCER",
                Self::Consumer => "CONSUMER",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "SPAN_KIND_UNSPECIFIED" => Some(Self::SpanKindUnspecified),
                "CLIENT" => Some(Self::Client),
                "SERVER" => Some(Self::Server),
                "PRODUCER" => Some(Self::Producer),
                "CONSUMER" => Some(Self::Consumer),
                _ => None,
            }
        }
    }
}
/// The network context of a node in the service graph.
///
/// The next id is 5.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Endpoint {
    /// Lower-case label of this node in the service graph, such as "favstar".
    /// Leave absent if unknown.
    ///
    /// This is a primary label for trace lookup and aggregation, so it should be
    /// intuitive and consistent. Many use a name from service discovery.
    #[prost(string, tag = "1")]
    pub service_name: ::prost::alloc::string::String,
    /// 4 byte representation of the primary IPv4 address associated with this
    /// connection. Absent if unknown.
    #[prost(bytes = "vec", tag = "2")]
    pub ipv4: ::prost::alloc::vec::Vec<u8>,
    /// 16 byte representation of the primary IPv6 address associated with this
    /// connection. Absent if unknown.
    ///
    /// Prefer using the ipv4 field for mapped addresses.
    #[prost(bytes = "vec", tag = "3")]
    pub ipv6: ::prost::alloc::vec::Vec<u8>,
    /// Depending on context, this could be a listen port or the client-side of a
    /// socket. Absent if unknown.
    #[prost(int32, tag = "4")]
    pub port: i32,
}
/// Associates an event that explains latency with a timestamp.
/// Unlike log statements, annotations are often codes. Ex. "ws" for WireSend
///
/// The next id is 3.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Annotation {
    /// Epoch microseconds of this event.
    ///
    /// For example, 1502787600000000 corresponds to 2017-08-15 09:00 UTC
    ///
    /// This value should be set directly by instrumentation, using the most
    /// precise value possible. For example, gettimeofday or multiplying epoch
    /// millis by 1000.
    #[prost(fixed64, tag = "1")]
    pub timestamp: u64,
    /// Usually a short tag indicating an event, like "error"
    ///
    /// While possible to add larger data, such as garbage collection details, low
    /// cardinality event names both keep the size of spans down and also are easy
    /// to search against.
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
}
/// A list of spans with possibly different trace ids, in no particular order.
///
/// This is used for all transports: POST, Kafka messages etc. No other fields
/// are expected, This message facilitates the mechanics of encoding a list, as
/// a field number is required. The name of this type is the same in the OpenApi
/// aka Swagger specification. <https://zipkin.io/zipkin-api/#/default/post_spans>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListOfSpans {
    #[prost(message, repeated, tag = "1")]
    pub spans: ::prost::alloc::vec::Vec<Span>,
}
// @@protoc_insertion_point(module)
