// @generated
// This file is @generated by prost-build.
/// Params defines the ratelimit module's parameters.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Params {
}
// @@protoc_insertion_point(module)
