// @generated
// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GoEnum {
    #[prost(enumeration = "Foo", required, tag = "1")]
    pub foo: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GoTestField {
    #[prost(string, required, tag = "1")]
    pub label: ::prost::alloc::string::String,
    #[prost(string, required, tag = "2")]
    pub r#type: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GoTest {
    /// Some typical parameters
    #[prost(enumeration = "go_test::Kind", required, tag = "1")]
    pub kind: i32,
    #[prost(string, optional, tag = "2")]
    pub table: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub param: ::core::option::Option<i32>,
    /// Required, repeated and optional foreign fields.
    #[prost(message, required, tag = "4")]
    pub required_field: GoTestField,
    #[prost(message, repeated, tag = "5")]
    pub repeated_field: ::prost::alloc::vec::Vec<GoTestField>,
    #[prost(message, optional, tag = "6")]
    pub optional_field: ::core::option::Option<GoTestField>,
    /// Required fields of all basic types
    #[prost(bool, required, tag = "10")]
    pub f_bool_required: bool,
    #[prost(int32, required, tag = "11")]
    pub f_int32_required: i32,
    #[prost(int64, required, tag = "12")]
    pub f_int64_required: i64,
    #[prost(fixed32, required, tag = "13")]
    pub f_fixed32_required: u32,
    #[prost(fixed64, required, tag = "14")]
    pub f_fixed64_required: u64,
    #[prost(uint32, required, tag = "15")]
    pub f_uint32_required: u32,
    #[prost(uint64, required, tag = "16")]
    pub f_uint64_required: u64,
    #[prost(float, required, tag = "17")]
    pub f_float_required: f32,
    #[prost(double, required, tag = "18")]
    pub f_double_required: f64,
    #[prost(string, required, tag = "19")]
    pub f_string_required: ::prost::alloc::string::String,
    #[prost(bytes = "vec", required, tag = "101")]
    pub f_bytes_required: ::prost::alloc::vec::Vec<u8>,
    #[prost(sint32, required, tag = "102")]
    pub f_sint32_required: i32,
    #[prost(sint64, required, tag = "103")]
    pub f_sint64_required: i64,
    #[prost(sfixed32, required, tag = "104")]
    pub f_sfixed32_required: i32,
    #[prost(sfixed64, required, tag = "105")]
    pub f_sfixed64_required: i64,
    /// Repeated fields of all basic types
    #[prost(bool, repeated, packed = "false", tag = "20")]
    pub f_bool_repeated: ::prost::alloc::vec::Vec<bool>,
    #[prost(int32, repeated, packed = "false", tag = "21")]
    pub f_int32_repeated: ::prost::alloc::vec::Vec<i32>,
    #[prost(int64, repeated, packed = "false", tag = "22")]
    pub f_int64_repeated: ::prost::alloc::vec::Vec<i64>,
    #[prost(fixed32, repeated, packed = "false", tag = "23")]
    pub f_fixed32_repeated: ::prost::alloc::vec::Vec<u32>,
    #[prost(fixed64, repeated, packed = "false", tag = "24")]
    pub f_fixed64_repeated: ::prost::alloc::vec::Vec<u64>,
    #[prost(uint32, repeated, packed = "false", tag = "25")]
    pub f_uint32_repeated: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint64, repeated, packed = "false", tag = "26")]
    pub f_uint64_repeated: ::prost::alloc::vec::Vec<u64>,
    #[prost(float, repeated, packed = "false", tag = "27")]
    pub f_float_repeated: ::prost::alloc::vec::Vec<f32>,
    #[prost(double, repeated, packed = "false", tag = "28")]
    pub f_double_repeated: ::prost::alloc::vec::Vec<f64>,
    #[prost(string, repeated, tag = "29")]
    pub f_string_repeated: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bytes = "vec", repeated, tag = "201")]
    pub f_bytes_repeated: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(sint32, repeated, packed = "false", tag = "202")]
    pub f_sint32_repeated: ::prost::alloc::vec::Vec<i32>,
    #[prost(sint64, repeated, packed = "false", tag = "203")]
    pub f_sint64_repeated: ::prost::alloc::vec::Vec<i64>,
    #[prost(sfixed32, repeated, packed = "false", tag = "204")]
    pub f_sfixed32_repeated: ::prost::alloc::vec::Vec<i32>,
    #[prost(sfixed64, repeated, packed = "false", tag = "205")]
    pub f_sfixed64_repeated: ::prost::alloc::vec::Vec<i64>,
    /// Optional fields of all basic types
    #[prost(bool, optional, tag = "30")]
    pub f_bool_optional: ::core::option::Option<bool>,
    #[prost(int32, optional, tag = "31")]
    pub f_int32_optional: ::core::option::Option<i32>,
    #[prost(int64, optional, tag = "32")]
    pub f_int64_optional: ::core::option::Option<i64>,
    #[prost(fixed32, optional, tag = "33")]
    pub f_fixed32_optional: ::core::option::Option<u32>,
    #[prost(fixed64, optional, tag = "34")]
    pub f_fixed64_optional: ::core::option::Option<u64>,
    #[prost(uint32, optional, tag = "35")]
    pub f_uint32_optional: ::core::option::Option<u32>,
    #[prost(uint64, optional, tag = "36")]
    pub f_uint64_optional: ::core::option::Option<u64>,
    #[prost(float, optional, tag = "37")]
    pub f_float_optional: ::core::option::Option<f32>,
    #[prost(double, optional, tag = "38")]
    pub f_double_optional: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "39")]
    pub f_string_optional: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes = "vec", optional, tag = "301")]
    pub f_bytes_optional: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(sint32, optional, tag = "302")]
    pub f_sint32_optional: ::core::option::Option<i32>,
    #[prost(sint64, optional, tag = "303")]
    pub f_sint64_optional: ::core::option::Option<i64>,
    #[prost(sfixed32, optional, tag = "304")]
    pub f_sfixed32_optional: ::core::option::Option<i32>,
    #[prost(sfixed64, optional, tag = "305")]
    pub f_sfixed64_optional: ::core::option::Option<i64>,
    /// Default-valued fields of all basic types
    #[prost(bool, optional, tag = "40", default = "true")]
    pub f_bool_defaulted: ::core::option::Option<bool>,
    #[prost(int32, optional, tag = "41", default = "32")]
    pub f_int32_defaulted: ::core::option::Option<i32>,
    #[prost(int64, optional, tag = "42", default = "64")]
    pub f_int64_defaulted: ::core::option::Option<i64>,
    #[prost(fixed32, optional, tag = "43", default = "320")]
    pub f_fixed32_defaulted: ::core::option::Option<u32>,
    #[prost(fixed64, optional, tag = "44", default = "640")]
    pub f_fixed64_defaulted: ::core::option::Option<u64>,
    #[prost(uint32, optional, tag = "45", default = "3200")]
    pub f_uint32_defaulted: ::core::option::Option<u32>,
    #[prost(uint64, optional, tag = "46", default = "6400")]
    pub f_uint64_defaulted: ::core::option::Option<u64>,
    #[prost(float, optional, tag = "47", default = "314159")]
    pub f_float_defaulted: ::core::option::Option<f32>,
    #[prost(double, optional, tag = "48", default = "271828")]
    pub f_double_defaulted: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "49", default = "hello, \"world!\"\n")]
    pub f_string_defaulted: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes = "vec", optional, tag = "401", default = "b\"Bignose\"")]
    pub f_bytes_defaulted: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(sint32, optional, tag = "402", default = "-32")]
    pub f_sint32_defaulted: ::core::option::Option<i32>,
    #[prost(sint64, optional, tag = "403", default = "-64")]
    pub f_sint64_defaulted: ::core::option::Option<i64>,
    #[prost(sfixed32, optional, tag = "404", default = "-32")]
    pub f_sfixed32_defaulted: ::core::option::Option<i32>,
    #[prost(sfixed64, optional, tag = "405", default = "-64")]
    pub f_sfixed64_defaulted: ::core::option::Option<i64>,
    /// Packed repeated fields (no string or bytes).
    #[prost(bool, repeated, tag = "50")]
    pub f_bool_repeated_packed: ::prost::alloc::vec::Vec<bool>,
    #[prost(int32, repeated, tag = "51")]
    pub f_int32_repeated_packed: ::prost::alloc::vec::Vec<i32>,
    #[prost(int64, repeated, tag = "52")]
    pub f_int64_repeated_packed: ::prost::alloc::vec::Vec<i64>,
    #[prost(fixed32, repeated, tag = "53")]
    pub f_fixed32_repeated_packed: ::prost::alloc::vec::Vec<u32>,
    #[prost(fixed64, repeated, tag = "54")]
    pub f_fixed64_repeated_packed: ::prost::alloc::vec::Vec<u64>,
    #[prost(uint32, repeated, tag = "55")]
    pub f_uint32_repeated_packed: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint64, repeated, tag = "56")]
    pub f_uint64_repeated_packed: ::prost::alloc::vec::Vec<u64>,
    #[prost(float, repeated, tag = "57")]
    pub f_float_repeated_packed: ::prost::alloc::vec::Vec<f32>,
    #[prost(double, repeated, tag = "58")]
    pub f_double_repeated_packed: ::prost::alloc::vec::Vec<f64>,
    #[prost(sint32, repeated, tag = "502")]
    pub f_sint32_repeated_packed: ::prost::alloc::vec::Vec<i32>,
    #[prost(sint64, repeated, tag = "503")]
    pub f_sint64_repeated_packed: ::prost::alloc::vec::Vec<i64>,
    #[prost(sfixed32, repeated, tag = "504")]
    pub f_sfixed32_repeated_packed: ::prost::alloc::vec::Vec<i32>,
    #[prost(sfixed64, repeated, tag = "505")]
    pub f_sfixed64_repeated_packed: ::prost::alloc::vec::Vec<i64>,
    #[prost(group, required, tag = "70")]
    pub requiredgroup: go_test::RequiredGroup,
    #[prost(group, repeated, tag = "80")]
    pub repeatedgroup: ::prost::alloc::vec::Vec<go_test::RepeatedGroup>,
    #[prost(group, optional, tag = "90")]
    pub optionalgroup: ::core::option::Option<go_test::OptionalGroup>,
}
/// Nested message and enum types in `GoTest`.
pub mod go_test {
    /// Required, repeated, and optional groups.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct RequiredGroup {
        #[prost(string, required, tag = "71")]
        pub required_field: ::prost::alloc::string::String,
    }
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct RepeatedGroup {
        #[prost(string, required, tag = "81")]
        pub required_field: ::prost::alloc::string::String,
    }
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct OptionalGroup {
        #[prost(string, required, tag = "91")]
        pub required_field: ::prost::alloc::string::String,
    }
    /// An enum, for completeness.
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Kind {
        Void = 0,
        /// Basic types
        Bool = 1,
        Bytes = 2,
        Fingerprint = 3,
        Float = 4,
        Int = 5,
        String = 6,
        Time = 7,
        /// Groupings
        Tuple = 8,
        Array = 9,
        Map = 10,
        /// Table types
        Table = 11,
        /// Functions
        ///
        /// last tag
        Function = 12,
    }
    impl Kind {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Void => "VOID",
                Self::Bool => "BOOL",
                Self::Bytes => "BYTES",
                Self::Fingerprint => "FINGERPRINT",
                Self::Float => "FLOAT",
                Self::Int => "INT",
                Self::String => "STRING",
                Self::Time => "TIME",
                Self::Tuple => "TUPLE",
                Self::Array => "ARRAY",
                Self::Map => "MAP",
                Self::Table => "TABLE",
                Self::Function => "FUNCTION",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "VOID" => Some(Self::Void),
                "BOOL" => Some(Self::Bool),
                "BYTES" => Some(Self::Bytes),
                "FINGERPRINT" => Some(Self::Fingerprint),
                "FLOAT" => Some(Self::Float),
                "INT" => Some(Self::Int),
                "STRING" => Some(Self::String),
                "TIME" => Some(Self::Time),
                "TUPLE" => Some(Self::Tuple),
                "ARRAY" => Some(Self::Array),
                "MAP" => Some(Self::Map),
                "TABLE" => Some(Self::Table),
                "FUNCTION" => Some(Self::Function),
                _ => None,
            }
        }
    }
}
/// For testing a group containing a required field.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GoTestRequiredGroupField {
    #[prost(group, required, tag = "1")]
    pub group: go_test_required_group_field::Group,
}
/// Nested message and enum types in `GoTestRequiredGroupField`.
pub mod go_test_required_group_field {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Group {
        #[prost(int32, required, tag = "2")]
        pub field: i32,
    }
}
/// For testing skipping of unrecognized fields.
/// Numbers are all big, larger than tag numbers in GoTestField,
/// the message used in the corresponding test.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GoSkipTest {
    #[prost(int32, required, tag = "11")]
    pub skip_int32: i32,
    #[prost(fixed32, required, tag = "12")]
    pub skip_fixed32: u32,
    #[prost(fixed64, required, tag = "13")]
    pub skip_fixed64: u64,
    #[prost(string, required, tag = "14")]
    pub skip_string: ::prost::alloc::string::String,
    #[prost(group, required, tag = "15")]
    pub skipgroup: go_skip_test::SkipGroup,
}
/// Nested message and enum types in `GoSkipTest`.
pub mod go_skip_test {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct SkipGroup {
        #[prost(int32, required, tag = "16")]
        pub group_int32: i32,
        #[prost(string, required, tag = "17")]
        pub group_string: ::prost::alloc::string::String,
    }
}
/// For testing packed/non-packed decoder switching.
/// A serialized instance of one should be deserializable as the other.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NonPackedTest {
    #[prost(int32, repeated, packed = "false", tag = "1")]
    pub a: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PackedTest {
    #[prost(int32, repeated, tag = "1")]
    pub b: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MaxTag {
    /// Maximum possible tag number.
    #[prost(string, optional, tag = "536870911")]
    pub last_field: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OldMessage {
    #[prost(message, optional, tag = "1")]
    pub nested: ::core::option::Option<old_message::Nested>,
    #[prost(int32, optional, tag = "2")]
    pub num: ::core::option::Option<i32>,
}
/// Nested message and enum types in `OldMessage`.
pub mod old_message {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Nested {
        #[prost(string, optional, tag = "1")]
        pub name: ::core::option::Option<::prost::alloc::string::String>,
    }
}
/// NewMessage is wire compatible with OldMessage;
/// imagine it as a future version.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NewMessage {
    #[prost(message, optional, tag = "1")]
    pub nested: ::core::option::Option<new_message::Nested>,
    /// This is an int32 in OldMessage.
    #[prost(int64, optional, tag = "2")]
    pub num: ::core::option::Option<i64>,
}
/// Nested message and enum types in `NewMessage`.
pub mod new_message {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Nested {
        #[prost(string, optional, tag = "1")]
        pub name: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "2")]
        pub food_group: ::core::option::Option<::prost::alloc::string::String>,
    }
}
// Smaller tests for ASCII formatting.

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InnerMessage {
    #[prost(string, required, tag = "1")]
    pub host: ::prost::alloc::string::String,
    #[prost(int32, optional, tag = "2", default = "4000")]
    pub port: ::core::option::Option<i32>,
    #[prost(bool, optional, tag = "3")]
    pub connected: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OtherMessage {
    #[prost(int64, optional, tag = "1")]
    pub key: ::core::option::Option<i64>,
    #[prost(bytes = "vec", optional, tag = "2")]
    pub value: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(float, optional, tag = "3")]
    pub weight: ::core::option::Option<f32>,
    #[prost(message, optional, tag = "4")]
    pub inner: ::core::option::Option<InnerMessage>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequiredInnerMessage {
    #[prost(message, required, tag = "1")]
    pub leo_finally_won_an_oscar: InnerMessage,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MyMessage {
    #[prost(int32, required, tag = "1")]
    pub count: i32,
    #[prost(string, optional, tag = "2")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub quote: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "4")]
    pub pet: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "5")]
    pub inner: ::core::option::Option<InnerMessage>,
    #[prost(message, repeated, tag = "6")]
    pub others: ::prost::alloc::vec::Vec<OtherMessage>,
    #[prost(message, optional, tag = "13")]
    pub we_must_go_deeper: ::core::option::Option<RequiredInnerMessage>,
    #[prost(message, repeated, tag = "12")]
    pub rep_inner: ::prost::alloc::vec::Vec<InnerMessage>,
    #[prost(enumeration = "my_message::Color", optional, tag = "7")]
    pub bikeshed: ::core::option::Option<i32>,
    #[prost(group, optional, tag = "8")]
    pub somegroup: ::core::option::Option<my_message::SomeGroup>,
    /// This field becomes [][]byte in the generated code.
    #[prost(bytes = "vec", repeated, tag = "10")]
    pub rep_bytes: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(double, optional, tag = "11")]
    pub bigfloat: ::core::option::Option<f64>,
}
/// Nested message and enum types in `MyMessage`.
pub mod my_message {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct SomeGroup {
        #[prost(int32, optional, tag = "9")]
        pub group_field: ::core::option::Option<i32>,
    }
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Color {
        Red = 0,
        Green = 1,
        Blue = 2,
    }
    impl Color {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Red => "RED",
                Self::Green => "GREEN",
                Self::Blue => "BLUE",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "RED" => Some(Self::Red),
                "GREEN" => Some(Self::Green),
                "BLUE" => Some(Self::Blue),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Ext {
    #[prost(string, optional, tag = "1")]
    pub data: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(map = "int32, int32", tag = "2")]
    pub map_field: ::std::collections::HashMap<i32, i32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ComplexExtension {
    #[prost(int32, optional, tag = "1")]
    pub first: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "2")]
    pub second: ::core::option::Option<i32>,
    #[prost(int32, repeated, packed = "false", tag = "3")]
    pub third: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DefaultsMessage {
}
/// Nested message and enum types in `DefaultsMessage`.
pub mod defaults_message {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum DefaultsEnum {
        Zero = 0,
        One = 1,
        Two = 2,
    }
    impl DefaultsEnum {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Zero => "ZERO",
                Self::One => "ONE",
                Self::Two => "TWO",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "ZERO" => Some(Self::Zero),
                "ONE" => Some(Self::One),
                "TWO" => Some(Self::Two),
                _ => None,
            }
        }
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MyMessageSet {
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Empty {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessageList {
    #[prost(group, repeated, tag = "1")]
    pub message: ::prost::alloc::vec::Vec<message_list::Message>,
}
/// Nested message and enum types in `MessageList`.
pub mod message_list {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Message {
        #[prost(string, required, tag = "2")]
        pub name: ::prost::alloc::string::String,
        #[prost(int32, required, tag = "3")]
        pub count: i32,
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Strings {
    #[prost(string, optional, tag = "1")]
    pub string_field: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes = "vec", optional, tag = "2")]
    pub bytes_field: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Defaults {
    /// Default-valued fields of all basic types.
    /// Same as GoTest, but copied here to make testing easier.
    #[prost(bool, optional, tag = "1", default = "true")]
    pub f_bool: ::core::option::Option<bool>,
    #[prost(int32, optional, tag = "2", default = "32")]
    pub f_int32: ::core::option::Option<i32>,
    #[prost(int64, optional, tag = "3", default = "64")]
    pub f_int64: ::core::option::Option<i64>,
    #[prost(fixed32, optional, tag = "4", default = "320")]
    pub f_fixed32: ::core::option::Option<u32>,
    #[prost(fixed64, optional, tag = "5", default = "640")]
    pub f_fixed64: ::core::option::Option<u64>,
    #[prost(uint32, optional, tag = "6", default = "3200")]
    pub f_uint32: ::core::option::Option<u32>,
    #[prost(uint64, optional, tag = "7", default = "6400")]
    pub f_uint64: ::core::option::Option<u64>,
    #[prost(float, optional, tag = "8", default = "314159")]
    pub f_float: ::core::option::Option<f32>,
    #[prost(double, optional, tag = "9", default = "271828")]
    pub f_double: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "10", default = "hello, \"world!\"\n")]
    pub f_string: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes = "vec", optional, tag = "11", default = "b\"Bignose\"")]
    pub f_bytes: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(sint32, optional, tag = "12", default = "-32")]
    pub f_sint32: ::core::option::Option<i32>,
    #[prost(sint64, optional, tag = "13", default = "-64")]
    pub f_sint64: ::core::option::Option<i64>,
    #[prost(enumeration = "defaults::Color", optional, tag = "14", default = "Green")]
    pub f_enum: ::core::option::Option<i32>,
    /// More fields with crazy defaults.
    #[prost(float, optional, tag = "15", default = "inf")]
    pub f_pinf: ::core::option::Option<f32>,
    #[prost(float, optional, tag = "16", default = "-inf")]
    pub f_ninf: ::core::option::Option<f32>,
    #[prost(float, optional, tag = "17", default = "nan")]
    pub f_nan: ::core::option::Option<f32>,
    /// Sub-message.
    #[prost(message, optional, tag = "18")]
    pub sub: ::core::option::Option<SubDefaults>,
    /// Redundant but explicit defaults.
    #[prost(string, optional, tag = "19", default = "")]
    pub str_zero: ::core::option::Option<::prost::alloc::string::String>,
}
/// Nested message and enum types in `Defaults`.
pub mod defaults {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Color {
        Red = 0,
        Green = 1,
        Blue = 2,
    }
    impl Color {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Red => "RED",
                Self::Green => "GREEN",
                Self::Blue => "BLUE",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "RED" => Some(Self::Red),
                "GREEN" => Some(Self::Green),
                "BLUE" => Some(Self::Blue),
                _ => None,
            }
        }
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubDefaults {
    #[prost(int64, optional, tag = "1", default = "7")]
    pub n: ::core::option::Option<i64>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RepeatedEnum {
    #[prost(enumeration = "repeated_enum::Color", repeated, packed = "false", tag = "1")]
    pub color: ::prost::alloc::vec::Vec<i32>,
}
/// Nested message and enum types in `RepeatedEnum`.
pub mod repeated_enum {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Color {
        Red = 1,
    }
    impl Color {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Red => "RED",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "RED" => Some(Self::Red),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MoreRepeated {
    #[prost(bool, repeated, packed = "false", tag = "1")]
    pub bools: ::prost::alloc::vec::Vec<bool>,
    #[prost(bool, repeated, tag = "2")]
    pub bools_packed: ::prost::alloc::vec::Vec<bool>,
    #[prost(int32, repeated, packed = "false", tag = "3")]
    pub ints: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, repeated, tag = "4")]
    pub ints_packed: ::prost::alloc::vec::Vec<i32>,
    #[prost(int64, repeated, tag = "7")]
    pub int64s_packed: ::prost::alloc::vec::Vec<i64>,
    #[prost(string, repeated, tag = "5")]
    pub strings: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(fixed32, repeated, packed = "false", tag = "6")]
    pub fixeds: ::prost::alloc::vec::Vec<u32>,
}
// GroupOld and GroupNew have the same wire format.
// GroupNew has a new field inside a group.

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GroupOld {
    #[prost(group, optional, tag = "101")]
    pub g: ::core::option::Option<group_old::G>,
}
/// Nested message and enum types in `GroupOld`.
pub mod group_old {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct G {
        #[prost(int32, optional, tag = "2")]
        pub x: ::core::option::Option<i32>,
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GroupNew {
    #[prost(group, optional, tag = "101")]
    pub g: ::core::option::Option<group_new::G>,
}
/// Nested message and enum types in `GroupNew`.
pub mod group_new {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct G {
        #[prost(int32, optional, tag = "2")]
        pub x: ::core::option::Option<i32>,
        #[prost(int32, optional, tag = "3")]
        pub y: ::core::option::Option<i32>,
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct FloatingPoint {
    #[prost(double, required, tag = "1")]
    pub f: f64,
    #[prost(bool, optional, tag = "2")]
    pub exact: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessageWithMap {
    #[prost(map = "int32, string", tag = "1")]
    pub name_mapping: ::std::collections::HashMap<i32, ::prost::alloc::string::String>,
    #[prost(map = "sint64, message", tag = "2")]
    pub msg_mapping: ::std::collections::HashMap<i64, FloatingPoint>,
    #[prost(map = "bool, bytes", tag = "3")]
    pub byte_mapping: ::std::collections::HashMap<bool, ::prost::alloc::vec::Vec<u8>>,
    #[prost(map = "string, string", tag = "4")]
    pub str_to_str: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Oneof {
    #[prost(oneof = "oneof::Union", tags = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 536870911")]
    pub union: ::core::option::Option<oneof::Union>,
    #[prost(oneof = "oneof::Tormato", tags = "100")]
    pub tormato: ::core::option::Option<oneof::Tormato>,
}
/// Nested message and enum types in `Oneof`.
pub mod oneof {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct FGroup {
        #[prost(int32, optional, tag = "17")]
        pub x: ::core::option::Option<i32>,
    }
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Union {
        #[prost(bool, tag = "1")]
        FBool(bool),
        #[prost(int32, tag = "2")]
        FInt32(i32),
        #[prost(int64, tag = "3")]
        FInt64(i64),
        #[prost(fixed32, tag = "4")]
        FFixed32(u32),
        #[prost(fixed64, tag = "5")]
        FFixed64(u64),
        #[prost(uint32, tag = "6")]
        FUint32(u32),
        #[prost(uint64, tag = "7")]
        FUint64(u64),
        #[prost(float, tag = "8")]
        FFloat(f32),
        #[prost(double, tag = "9")]
        FDouble(f64),
        #[prost(string, tag = "10")]
        FString(::prost::alloc::string::String),
        #[prost(bytes, tag = "11")]
        FBytes(::prost::alloc::vec::Vec<u8>),
        #[prost(sint32, tag = "12")]
        FSint32(i32),
        #[prost(sint64, tag = "13")]
        FSint64(i64),
        #[prost(enumeration = "super::my_message::Color", tag = "14")]
        FEnum(i32),
        #[prost(message, tag = "15")]
        FMessage(super::GoTestField),
        #[prost(group, tag = "16")]
        FGroup(FGroup),
        #[prost(int32, tag = "536870911")]
        FLargestTag(i32),
    }
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Tormato {
        #[prost(int32, tag = "100")]
        Value(i32),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Communique {
    #[prost(bool, optional, tag = "1")]
    pub make_me_cry: ::core::option::Option<bool>,
    /// This is a oneof, called "union".
    #[prost(oneof = "communique::Union", tags = "5, 6, 7, 8, 9, 10")]
    pub union: ::core::option::Option<communique::Union>,
}
/// Nested message and enum types in `Communique`.
pub mod communique {
    /// This is a oneof, called "union".
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Union {
        #[prost(int32, tag = "5")]
        Number(i32),
        #[prost(string, tag = "6")]
        Name(::prost::alloc::string::String),
        #[prost(bytes, tag = "7")]
        Data(::prost::alloc::vec::Vec<u8>),
        #[prost(double, tag = "8")]
        TempC(f64),
        #[prost(enumeration = "super::my_message::Color", tag = "9")]
        Col(i32),
        #[prost(message, tag = "10")]
        Msg(super::Strings),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TestUtf8 {
    #[prost(string, optional, tag = "1")]
    pub scalar: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "2")]
    pub vector: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(map = "string, int64", tag = "4")]
    pub map_key: ::std::collections::HashMap<::prost::alloc::string::String, i64>,
    #[prost(map = "int64, string", tag = "5")]
    pub map_value: ::std::collections::HashMap<i64, ::prost::alloc::string::String>,
    #[prost(oneof = "test_utf8::Oneof", tags = "3")]
    pub oneof: ::core::option::Option<test_utf8::Oneof>,
}
/// Nested message and enum types in `TestUTF8`.
pub mod test_utf8 {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Oneof {
        #[prost(string, tag = "3")]
        Field(::prost::alloc::string::String),
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Foo {
    Foo1 = 1,
}
impl Foo {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Foo1 => "FOO1",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "FOO1" => Some(Self::Foo1),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
