// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.32.0
// source: ibc/lightclients/wasm/v1/tx.proto

package types

import (
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MsgStoreCode defines the request type for the StoreCode rpc.
type MsgStoreCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// signer address
	Signer string `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	// wasm byte code of light client contract. It can be raw or gzip compressed
	WasmByteCode []byte `protobuf:"bytes,2,opt,name=wasm_byte_code,json=wasmByteCode,proto3" json:"wasm_byte_code,omitempty"`
}

func (x *MsgStoreCode) Reset() {
	*x = MsgStoreCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ibc_lightclients_wasm_v1_tx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgStoreCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgStoreCode) ProtoMessage() {}

func (x *MsgStoreCode) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_lightclients_wasm_v1_tx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgStoreCode.ProtoReflect.Descriptor instead.
func (*MsgStoreCode) Descriptor() ([]byte, []int) {
	return file_ibc_lightclients_wasm_v1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgStoreCode) GetSigner() string {
	if x != nil {
		return x.Signer
	}
	return ""
}

func (x *MsgStoreCode) GetWasmByteCode() []byte {
	if x != nil {
		return x.WasmByteCode
	}
	return nil
}

// MsgStoreCodeResponse defines the response type for the StoreCode rpc
type MsgStoreCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// checksum is the sha256 hash of the stored code
	Checksum []byte `protobuf:"bytes,1,opt,name=checksum,proto3" json:"checksum,omitempty"`
}

func (x *MsgStoreCodeResponse) Reset() {
	*x = MsgStoreCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ibc_lightclients_wasm_v1_tx_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgStoreCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgStoreCodeResponse) ProtoMessage() {}

func (x *MsgStoreCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_lightclients_wasm_v1_tx_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgStoreCodeResponse.ProtoReflect.Descriptor instead.
func (*MsgStoreCodeResponse) Descriptor() ([]byte, []int) {
	return file_ibc_lightclients_wasm_v1_tx_proto_rawDescGZIP(), []int{1}
}

func (x *MsgStoreCodeResponse) GetChecksum() []byte {
	if x != nil {
		return x.Checksum
	}
	return nil
}

// MsgRemoveChecksum defines the request type for the MsgRemoveChecksum rpc.
type MsgRemoveChecksum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// signer address
	Signer string `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	// checksum is the sha256 hash to be removed from the store
	Checksum []byte `protobuf:"bytes,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
}

func (x *MsgRemoveChecksum) Reset() {
	*x = MsgRemoveChecksum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ibc_lightclients_wasm_v1_tx_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgRemoveChecksum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRemoveChecksum) ProtoMessage() {}

func (x *MsgRemoveChecksum) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_lightclients_wasm_v1_tx_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRemoveChecksum.ProtoReflect.Descriptor instead.
func (*MsgRemoveChecksum) Descriptor() ([]byte, []int) {
	return file_ibc_lightclients_wasm_v1_tx_proto_rawDescGZIP(), []int{2}
}

func (x *MsgRemoveChecksum) GetSigner() string {
	if x != nil {
		return x.Signer
	}
	return ""
}

func (x *MsgRemoveChecksum) GetChecksum() []byte {
	if x != nil {
		return x.Checksum
	}
	return nil
}

// MsgStoreChecksumResponse defines the response type for the StoreCode rpc
type MsgRemoveChecksumResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MsgRemoveChecksumResponse) Reset() {
	*x = MsgRemoveChecksumResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ibc_lightclients_wasm_v1_tx_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgRemoveChecksumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRemoveChecksumResponse) ProtoMessage() {}

func (x *MsgRemoveChecksumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_lightclients_wasm_v1_tx_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRemoveChecksumResponse.ProtoReflect.Descriptor instead.
func (*MsgRemoveChecksumResponse) Descriptor() ([]byte, []int) {
	return file_ibc_lightclients_wasm_v1_tx_proto_rawDescGZIP(), []int{3}
}

// MsgMigrateContract defines the request type for the MigrateContract rpc.
type MsgMigrateContract struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// signer address
	Signer string `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	// the client id of the contract
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// checksum is the sha256 hash of the new wasm byte code for the contract
	Checksum []byte `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	// the json encoded message to be passed to the contract on migration
	Msg []byte `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *MsgMigrateContract) Reset() {
	*x = MsgMigrateContract{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ibc_lightclients_wasm_v1_tx_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgMigrateContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgMigrateContract) ProtoMessage() {}

func (x *MsgMigrateContract) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_lightclients_wasm_v1_tx_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgMigrateContract.ProtoReflect.Descriptor instead.
func (*MsgMigrateContract) Descriptor() ([]byte, []int) {
	return file_ibc_lightclients_wasm_v1_tx_proto_rawDescGZIP(), []int{4}
}

func (x *MsgMigrateContract) GetSigner() string {
	if x != nil {
		return x.Signer
	}
	return ""
}

func (x *MsgMigrateContract) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *MsgMigrateContract) GetChecksum() []byte {
	if x != nil {
		return x.Checksum
	}
	return nil
}

func (x *MsgMigrateContract) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

// MsgMigrateContractResponse defines the response type for the MigrateContract rpc
type MsgMigrateContractResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MsgMigrateContractResponse) Reset() {
	*x = MsgMigrateContractResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ibc_lightclients_wasm_v1_tx_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgMigrateContractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgMigrateContractResponse) ProtoMessage() {}

func (x *MsgMigrateContractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_lightclients_wasm_v1_tx_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgMigrateContractResponse.ProtoReflect.Descriptor instead.
func (*MsgMigrateContractResponse) Descriptor() ([]byte, []int) {
	return file_ibc_lightclients_wasm_v1_tx_proto_rawDescGZIP(), []int{5}
}

var File_ibc_lightclients_wasm_v1_tx_proto protoreflect.FileDescriptor

var file_ibc_lightclients_wasm_v1_tx_proto_rawDesc = []byte{
	0x0a, 0x21, 0x69, 0x62, 0x63, 0x2f, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x73, 0x2f, 0x77, 0x61, 0x73, 0x6d, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x78, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x18, 0x69, 0x62, 0x63, 0x2e, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x76, 0x31, 0x1a, 0x17, 0x63,
	0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2f, 0x6d, 0x73, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x73, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x59, 0x0a, 0x0c, 0x4d, 0x73, 0x67, 0x53, 0x74, 0x6f,
	0x72, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x12, 0x24,
	0x0a, 0x0e, 0x77, 0x61, 0x73, 0x6d, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x77, 0x61, 0x73, 0x6d, 0x42, 0x79, 0x74, 0x65,
	0x43, 0x6f, 0x64, 0x65, 0x3a, 0x0b, 0x82, 0xe7, 0xb0, 0x2a, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x65,
	0x72, 0x22, 0x32, 0x0a, 0x14, 0x4d, 0x73, 0x67, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68, 0x65,
	0x63, 0x6b, 0x73, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x63, 0x68, 0x65,
	0x63, 0x6b, 0x73, 0x75, 0x6d, 0x22, 0x54, 0x0a, 0x11, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x69,
	0x67, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x69, 0x67, 0x6e,
	0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x3a, 0x0b,
	0x82, 0xe7, 0xb0, 0x2a, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x22, 0x1b, 0x0a, 0x19, 0x4d,
	0x73, 0x67, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x84, 0x01, 0x0a, 0x12, 0x4d, 0x73, 0x67,
	0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x3a, 0x0b, 0x82, 0xe7, 0xb0, 0x2a, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x22,
	0x1c, 0x0a, 0x1a, 0x4d, 0x73, 0x67, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xdc, 0x02,
	0x0a, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x63, 0x0a, 0x09, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x26, 0x2e, 0x69, 0x62, 0x63, 0x2e, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x73,
	0x67, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x1a, 0x2e, 0x2e, 0x69, 0x62, 0x63,
	0x2e, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x77, 0x61,
	0x73, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x73, 0x67, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x72, 0x0a, 0x0e, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x12, 0x2b, 0x2e, 0x69,
	0x62, 0x63, 0x2e, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x2e,
	0x77, 0x61, 0x73, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x1a, 0x33, 0x2e, 0x69, 0x62, 0x63, 0x2e,
	0x6c, 0x69, 0x67, 0x68, 0x74, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x77, 0x61, 0x73,
	0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x75,
	0x0a, 0x0f, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x12, 0x2c, 0x2e, 0x69, 0x62, 0x63, 0x2e, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x73, 0x2e, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x73, 0x67,
	0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x1a,
	0x34, 0x2e, 0x69, 0x62, 0x63, 0x2e, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x73, 0x2e, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x73, 0x67, 0x4d, 0x69,
	0x67, 0x72, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x05, 0x80, 0xe7, 0xb0, 0x2a, 0x01, 0x42, 0x42, 0x5a, 0x40,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x73, 0x6d, 0x6f,
	0x73, 0x2f, 0x69, 0x62, 0x63, 0x2d, 0x67, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73,
	0x2f, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x30,
	0x38, 0x2d, 0x77, 0x61, 0x73, 0x6d, 0x2f, 0x76, 0x31, 0x30, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ibc_lightclients_wasm_v1_tx_proto_rawDescOnce sync.Once
	file_ibc_lightclients_wasm_v1_tx_proto_rawDescData = file_ibc_lightclients_wasm_v1_tx_proto_rawDesc
)

func file_ibc_lightclients_wasm_v1_tx_proto_rawDescGZIP() []byte {
	file_ibc_lightclients_wasm_v1_tx_proto_rawDescOnce.Do(func() {
		file_ibc_lightclients_wasm_v1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(file_ibc_lightclients_wasm_v1_tx_proto_rawDescData)
	})
	return file_ibc_lightclients_wasm_v1_tx_proto_rawDescData
}

var file_ibc_lightclients_wasm_v1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_ibc_lightclients_wasm_v1_tx_proto_goTypes = []interface{}{
	(*MsgStoreCode)(nil),               // 0: ibc.lightclients.wasm.v1.MsgStoreCode
	(*MsgStoreCodeResponse)(nil),       // 1: ibc.lightclients.wasm.v1.MsgStoreCodeResponse
	(*MsgRemoveChecksum)(nil),          // 2: ibc.lightclients.wasm.v1.MsgRemoveChecksum
	(*MsgRemoveChecksumResponse)(nil),  // 3: ibc.lightclients.wasm.v1.MsgRemoveChecksumResponse
	(*MsgMigrateContract)(nil),         // 4: ibc.lightclients.wasm.v1.MsgMigrateContract
	(*MsgMigrateContractResponse)(nil), // 5: ibc.lightclients.wasm.v1.MsgMigrateContractResponse
}
var file_ibc_lightclients_wasm_v1_tx_proto_depIdxs = []int32{
	0, // 0: ibc.lightclients.wasm.v1.Msg.StoreCode:input_type -> ibc.lightclients.wasm.v1.MsgStoreCode
	2, // 1: ibc.lightclients.wasm.v1.Msg.RemoveChecksum:input_type -> ibc.lightclients.wasm.v1.MsgRemoveChecksum
	4, // 2: ibc.lightclients.wasm.v1.Msg.MigrateContract:input_type -> ibc.lightclients.wasm.v1.MsgMigrateContract
	1, // 3: ibc.lightclients.wasm.v1.Msg.StoreCode:output_type -> ibc.lightclients.wasm.v1.MsgStoreCodeResponse
	3, // 4: ibc.lightclients.wasm.v1.Msg.RemoveChecksum:output_type -> ibc.lightclients.wasm.v1.MsgRemoveChecksumResponse
	5, // 5: ibc.lightclients.wasm.v1.Msg.MigrateContract:output_type -> ibc.lightclients.wasm.v1.MsgMigrateContractResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ibc_lightclients_wasm_v1_tx_proto_init() }
func file_ibc_lightclients_wasm_v1_tx_proto_init() {
	if File_ibc_lightclients_wasm_v1_tx_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ibc_lightclients_wasm_v1_tx_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgStoreCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ibc_lightclients_wasm_v1_tx_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgStoreCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ibc_lightclients_wasm_v1_tx_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgRemoveChecksum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ibc_lightclients_wasm_v1_tx_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgRemoveChecksumResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ibc_lightclients_wasm_v1_tx_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgMigrateContract); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ibc_lightclients_wasm_v1_tx_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgMigrateContractResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ibc_lightclients_wasm_v1_tx_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ibc_lightclients_wasm_v1_tx_proto_goTypes,
		DependencyIndexes: file_ibc_lightclients_wasm_v1_tx_proto_depIdxs,
		MessageInfos:      file_ibc_lightclients_wasm_v1_tx_proto_msgTypes,
	}.Build()
	File_ibc_lightclients_wasm_v1_tx_proto = out.File
	file_ibc_lightclients_wasm_v1_tx_proto_rawDesc = nil
	file_ibc_lightclients_wasm_v1_tx_proto_goTypes = nil
	file_ibc_lightclients_wasm_v1_tx_proto_depIdxs = nil
}
