// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Message {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(enumeration = "message::Humour", tag = "2")]
    pub hilarity: i32,
    #[prost(uint32, tag = "3")]
    pub height_in_cm: u32,
    #[prost(bytes = "vec", tag = "4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag = "7")]
    pub result_count: i64,
    #[prost(bool, tag = "8")]
    pub true_scotsman: bool,
    #[prost(float, tag = "9")]
    pub score: f32,
    #[prost(uint64, repeated, tag = "5")]
    pub key: ::prost::alloc::vec::Vec<u64>,
    #[prost(int32, repeated, tag = "19")]
    pub short_key: ::prost::alloc::vec::Vec<i32>,
    #[prost(message, optional, tag = "6")]
    pub nested: ::core::option::Option<Nested>,
    #[prost(enumeration = "message::Humour", repeated, tag = "16")]
    pub r_funny: ::prost::alloc::vec::Vec<i32>,
    #[prost(map = "string, message", tag = "10")]
    pub terrain: ::std::collections::HashMap<::prost::alloc::string::String, Nested>,
    #[prost(message, optional, tag = "11")]
    pub proto2_field: ::core::option::Option<super::test_proto::SubDefaults>,
    #[prost(map = "string, message", tag = "13")]
    pub proto2_value: ::std::collections::HashMap<::prost::alloc::string::String, super::test_proto::SubDefaults>,
    #[prost(message, optional, tag = "14")]
    pub anything: ::core::option::Option<::prost_types::Any>,
    #[prost(message, repeated, tag = "15")]
    pub many_things: ::prost::alloc::vec::Vec<::prost_types::Any>,
    #[prost(message, optional, boxed, tag = "17")]
    pub submessage: ::core::option::Option<::prost::alloc::boxed::Box<Message>>,
    #[prost(message, repeated, tag = "18")]
    pub children: ::prost::alloc::vec::Vec<Message>,
    #[prost(map = "string, string", tag = "20")]
    pub string_map: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
/// Nested message and enum types in `Message`.
pub mod message {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Humour {
        Unknown = 0,
        Puns = 1,
        Slapstick = 2,
        BillBailey = 3,
    }
    impl Humour {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unknown => "UNKNOWN",
                Self::Puns => "PUNS",
                Self::Slapstick => "SLAPSTICK",
                Self::BillBailey => "BILL_BAILEY",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "UNKNOWN" => Some(Self::Unknown),
                "PUNS" => Some(Self::Puns),
                "SLAPSTICK" => Some(Self::Slapstick),
                "BILL_BAILEY" => Some(Self::BillBailey),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Nested {
    #[prost(string, tag = "1")]
    pub bunny: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub cute: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessageWithMap {
    #[prost(map = "bool, bytes", tag = "1")]
    pub byte_mapping: ::std::collections::HashMap<bool, ::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IntMap {
    #[prost(map = "int32, int32", tag = "1")]
    pub rtt: ::std::collections::HashMap<i32, i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IntMaps {
    #[prost(message, repeated, tag = "1")]
    pub maps: ::prost::alloc::vec::Vec<IntMap>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TestUtf8 {
    #[prost(string, tag = "1")]
    pub scalar: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub vector: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(map = "string, int64", tag = "4")]
    pub map_key: ::std::collections::HashMap<::prost::alloc::string::String, i64>,
    #[prost(map = "int64, string", tag = "5")]
    pub map_value: ::std::collections::HashMap<i64, ::prost::alloc::string::String>,
    #[prost(oneof = "test_utf8::Oneof", tags = "3")]
    pub oneof: ::core::option::Option<test_utf8::Oneof>,
}
/// Nested message and enum types in `TestUTF8`.
pub mod test_utf8 {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Oneof {
        #[prost(string, tag = "3")]
        Field(::prost::alloc::string::String),
    }
}
// @@protoc_insertion_point(module)
