// @generated
// This file is @generated by prost-build.
/// BackfillStatus is a value used to keep track of the progress of the process
/// of backfilling blocks leading up to the origin block used to checkpoint sync
/// a node. There is only one BackfillStatus value in the database.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BackfillStatus {
    /// low_slot is the slot of the last block that backfill will attempt to
    /// download and import. This is determined by MIN_EPOCHS_FOR_BLOCK_REQUESTS,
    /// or by a user-specified override.
    #[prost(uint64, tag = "1")]
    pub low_slot: u64,
    /// low_root is the root of the last block that backfill will attempt to
    /// download and import.
    #[prost(bytes = "vec", tag = "2")]
    pub low_root: ::prost::alloc::vec::Vec<u8>,
    /// low_parent_root is the parent_root of the block at low_root. This enables
    /// the backfill service to check that a block is the direct ancestor of the
    /// block for low_root without an additional db lookup.
    #[prost(bytes = "vec", tag = "3")]
    pub low_parent_root: ::prost::alloc::vec::Vec<u8>,
    /// origin_slot is the slot of the origin block, which is the block used to
    /// initiate a checkpoint sync. Backfill uses the origin block as the reference
    /// point to determine canonical ancestors.
    #[prost(uint64, tag = "4")]
    pub origin_slot: u64,
    /// origin_root is the root of the origin block.
    #[prost(bytes = "vec", tag = "6")]
    pub origin_root: ::prost::alloc::vec::Vec<u8>,
}
// @@protoc_insertion_point(module)
