// @generated
// This file is @generated by prost-build.
/// Module is the config object of the IBC Rate Limiting module.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Module {
    /// authority defines the custom module authority.
    #[prost(string, tag = "1")]
    pub authority: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
