// @generated
// This file is @generated by prost-build.
/// Module is the config object of the nft module.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Module {
}
// @@protoc_insertion_point(module)
